// Master Calculator Registry
// Every calculator in the platform is registered here

export type CalculatorCategory = 'math' | 'finance' | 'health' | 'date-time' | 'conversion' | 'everyday'

export type CalculatorMode = 'retro' | 'form'

export interface CalculatorEntry {
  slug: string
  name: string
  shortName: string
  category: CalculatorCategory
  description: string
  keywords: string[]
  mode: CalculatorMode // primary UI mode
  icon: string // lucide icon name
}

export const CATEGORY_LABELS: Record<CalculatorCategory, string> = {
  math: 'Math',
  finance: 'Finance',
  health: 'Health & Fitness',
  'date-time': 'Date & Time',
  conversion: 'Conversion',
  everyday: 'Everyday Tools',
}

export const CATEGORY_COLORS: Record<CalculatorCategory, { bg: string; text: string; border: string }> = {
  math: { bg: 'bg-blue-50', text: 'text-blue-600', border: 'border-blue-200' },
  finance: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
  health: { bg: 'bg-rose-50', text: 'text-rose-600', border: 'border-rose-200' },
  'date-time': { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
  conversion: { bg: 'bg-emerald-50', text: 'text-emerald-600', border: 'border-emerald-200' },
  everyday: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200' },
}

export const calculators: CalculatorEntry[] = [
  // ═══════════════ MATH ═══════════════
  {
    slug: 'basic',
    name: 'Basic Calculator',
    shortName: 'Basic',
    category: 'math',
    description: 'Simple everyday arithmetic — add, subtract, multiply, divide with a retro LCD display.',
    keywords: ['basic calculator', 'simple calculator', 'arithmetic', 'add subtract multiply divide'],
    mode: 'retro',
    icon: 'Calculator',
  },
  {
    slug: 'scientific',
    name: 'Scientific Calculator',
    shortName: 'Scientific',
    category: 'math',
    description: 'Advanced scientific calculator with trigonometry, logarithms, powers, and constants.',
    keywords: ['scientific calculator', 'sin cos tan', 'logarithm', 'trigonometry'],
    mode: 'retro',
    icon: 'FlaskConical',
  },
  {
    slug: 'percentage',
    name: 'Percentage Calculator',
    shortName: 'Percentage',
    category: 'math',
    description: 'Calculate percentages: what is X% of Y, percentage change, and more.',
    keywords: ['percentage calculator', 'percent', 'percentage change', 'percentage increase decrease'],
    mode: 'form',
    icon: 'Percent',
  },
  {
    slug: 'fraction',
    name: 'Fraction Calculator',
    shortName: 'Fractions',
    category: 'math',
    description: 'Add, subtract, multiply, divide fractions. Simplify and convert to decimals.',
    keywords: ['fraction calculator', 'add fractions', 'simplify fraction'],
    mode: 'form',
    icon: 'Divide',
  },
  {
    slug: 'area',
    name: 'Area Calculator',
    shortName: 'Area',
    category: 'math',
    description: 'Calculate area of rectangles, circles, triangles, trapezoids, and ellipses.',
    keywords: ['area calculator', 'rectangle area', 'circle area', 'triangle area'],
    mode: 'form',
    icon: 'Square',
  },
  {
    slug: 'volume',
    name: 'Volume Calculator',
    shortName: 'Volume',
    category: 'math',
    description: 'Calculate volume of cubes, spheres, cylinders, cones, and pyramids.',
    keywords: ['volume calculator', 'cube volume', 'sphere volume', 'cylinder volume'],
    mode: 'form',
    icon: 'Box',
  },
  {
    slug: 'quadratic',
    name: 'Quadratic Equation Solver',
    shortName: 'Quadratic',
    category: 'math',
    description: 'Solve ax² + bx + c = 0. Find roots, discriminant, and vertex.',
    keywords: ['quadratic equation', 'solve quadratic', 'roots', 'discriminant'],
    mode: 'form',
    icon: 'TrendingUp',
  },
  {
    slug: 'statistics',
    name: 'Statistics Calculator',
    shortName: 'Statistics',
    category: 'math',
    description: 'Calculate mean, median, mode, standard deviation, and variance from a data set.',
    keywords: ['statistics calculator', 'mean', 'median', 'mode', 'standard deviation'],
    mode: 'form',
    icon: 'BarChart3',
  },
  {
    slug: 'gcd-lcm',
    name: 'GCD & LCM Calculator',
    shortName: 'GCD/LCM',
    category: 'math',
    description: 'Find the Greatest Common Divisor and Least Common Multiple of two or more numbers.',
    keywords: ['gcd calculator', 'lcm calculator', 'greatest common divisor', 'least common multiple'],
    mode: 'form',
    icon: 'GitMerge',
  },
  {
    slug: 'number-base',
    name: 'Number Base Converter',
    shortName: 'Base Convert',
    category: 'math',
    description: 'Convert between binary, octal, decimal, and hexadecimal number systems.',
    keywords: ['binary converter', 'hex converter', 'octal', 'number base'],
    mode: 'form',
    icon: 'Binary',
  },
  {
    slug: 'exponent',
    name: 'Exponent Calculator',
    shortName: 'Exponent',
    category: 'math',
    description: 'Calculate powers, roots, and exponential expressions.',
    keywords: ['exponent calculator', 'power calculator', 'roots'],
    mode: 'form',
    icon: 'Superscript',
  },
  {
    slug: 'permutation-combination',
    name: 'Permutation & Combination',
    shortName: 'nPr / nCr',
    category: 'math',
    description: 'Calculate permutations (nPr) and combinations (nCr) with factorial support.',
    keywords: ['permutation', 'combination', 'nPr', 'nCr', 'factorial'],
    mode: 'form',
    icon: 'Shuffle',
  },
  {
    slug: 'ratio',
    name: 'Ratio Calculator',
    shortName: 'Ratio',
    category: 'math',
    description: 'Simplify ratios, find equivalent ratios, and solve proportions.',
    keywords: ['ratio calculator', 'proportion', 'simplify ratio'],
    mode: 'form',
    icon: 'Scale',
  },
  {
    slug: 'logarithm',
    name: 'Logarithm Calculator',
    shortName: 'Logarithm',
    category: 'math',
    description: 'Calculate natural log (ln), common log (log₁₀), and log with custom base.',
    keywords: ['logarithm calculator', 'log', 'natural log', 'ln'],
    mode: 'form',
    icon: 'Activity',
  },

  // ═══════════════ FINANCE ═══════════════
  {
    slug: 'loan-emi',
    name: 'Loan EMI Calculator',
    shortName: 'Loan EMI',
    category: 'finance',
    description: 'Calculate monthly EMI, total interest, and payment schedule for any loan.',
    keywords: ['emi calculator', 'loan calculator', 'monthly payment', 'amortization'],
    mode: 'form',
    icon: 'Landmark',
  },
  {
    slug: 'compound-interest',
    name: 'Compound Interest Calculator',
    shortName: 'Compound Interest',
    category: 'finance',
    description: 'Calculate compound interest with flexible compounding frequencies.',
    keywords: ['compound interest', 'investment growth', 'compounding'],
    mode: 'form',
    icon: 'TrendingUp',
  },
  {
    slug: 'simple-interest',
    name: 'Simple Interest Calculator',
    shortName: 'Simple Interest',
    category: 'finance',
    description: 'Calculate simple interest: I = P × R × T.',
    keywords: ['simple interest', 'interest calculator'],
    mode: 'form',
    icon: 'Coins',
  },
  {
    slug: 'sip',
    name: 'SIP Calculator',
    shortName: 'SIP',
    category: 'finance',
    description: 'Systematic Investment Plan calculator — project your wealth growth over time.',
    keywords: ['sip calculator', 'mutual fund', 'investment plan'],
    mode: 'form',
    icon: 'PiggyBank',
  },
  {
    slug: 'tip',
    name: 'Tip Calculator',
    shortName: 'Tip',
    category: 'finance',
    description: 'Calculate tip amount and split bills between multiple people.',
    keywords: ['tip calculator', 'gratuity', 'bill split'],
    mode: 'form',
    icon: 'HandCoins',
  },
  {
    slug: 'discount',
    name: 'Discount Calculator',
    shortName: 'Discount',
    category: 'finance',
    description: 'Calculate discount amount, final price, and savings.',
    keywords: ['discount calculator', 'sale price', 'savings'],
    mode: 'form',
    icon: 'Tag',
  },
  {
    slug: 'profit-margin',
    name: 'Profit Margin Calculator',
    shortName: 'Profit Margin',
    category: 'finance',
    description: 'Calculate gross profit margin, net margin, and markup percentage.',
    keywords: ['profit margin', 'markup', 'gross margin'],
    mode: 'form',
    icon: 'Receipt',
  },
  {
    slug: 'roi',
    name: 'ROI Calculator',
    shortName: 'ROI',
    category: 'finance',
    description: 'Calculate Return on Investment with gain/loss analysis.',
    keywords: ['roi calculator', 'return on investment'],
    mode: 'form',
    icon: 'LineChart',
  },
  {
    slug: 'salary',
    name: 'Salary Calculator',
    shortName: 'Salary',
    category: 'finance',
    description: 'Convert between hourly, daily, weekly, monthly, and annual salary.',
    keywords: ['salary calculator', 'hourly to annual', 'wage converter'],
    mode: 'form',
    icon: 'Wallet',
  },
  {
    slug: 'mortgage',
    name: 'Mortgage Calculator',
    shortName: 'Mortgage',
    category: 'finance',
    description: 'Calculate monthly mortgage payments, total interest, and amortization.',
    keywords: ['mortgage calculator', 'home loan', 'house payment'],
    mode: 'form',
    icon: 'Home',
  },
  {
    slug: 'inflation',
    name: 'Inflation Calculator',
    shortName: 'Inflation',
    category: 'finance',
    description: 'Calculate the effect of inflation on purchasing power over time.',
    keywords: ['inflation calculator', 'purchasing power', 'cost of living'],
    mode: 'form',
    icon: 'TrendingDown',
  },
  {
    slug: 'break-even',
    name: 'Break-Even Calculator',
    shortName: 'Break-Even',
    category: 'finance',
    description: 'Find the break-even point — units and revenue needed to cover costs.',
    keywords: ['break even', 'breakeven analysis', 'cost analysis'],
    mode: 'form',
    icon: 'Target',
  },
  {
    slug: 'savings-goal',
    name: 'Savings Goal Calculator',
    shortName: 'Savings Goal',
    category: 'finance',
    description: 'How much to save monthly to reach your financial goal.',
    keywords: ['savings goal', 'savings calculator', 'financial planning'],
    mode: 'form',
    icon: 'Goal',
  },
  {
    slug: 'currency',
    name: 'Currency Converter',
    shortName: 'Currency',
    category: 'finance',
    description: 'Convert between major world currencies with approximate exchange rates.',
    keywords: ['currency converter', 'exchange rate', 'forex'],
    mode: 'form',
    icon: 'ArrowLeftRight',
  },

  // ═══════════════ HEALTH ═══════════════
  {
    slug: 'bmi',
    name: 'BMI Calculator',
    shortName: 'BMI',
    category: 'health',
    description: 'Calculate Body Mass Index with health category classification.',
    keywords: ['bmi calculator', 'body mass index', 'weight health'],
    mode: 'form',
    icon: 'Heart',
  },
  {
    slug: 'calorie',
    name: 'Calorie & TDEE Calculator',
    shortName: 'Calories',
    category: 'health',
    description: 'Calculate your Basal Metabolic Rate and Total Daily Energy Expenditure.',
    keywords: ['calorie calculator', 'bmr', 'tdee', 'metabolism'],
    mode: 'form',
    icon: 'Flame',
  },
  {
    slug: 'body-fat',
    name: 'Body Fat Calculator',
    shortName: 'Body Fat',
    category: 'health',
    description: 'Estimate body fat percentage using the US Navy method.',
    keywords: ['body fat calculator', 'body composition', 'navy method'],
    mode: 'form',
    icon: 'User',
  },
  {
    slug: 'ideal-weight',
    name: 'Ideal Weight Calculator',
    shortName: 'Ideal Weight',
    category: 'health',
    description: 'Find your ideal weight range using multiple scientific formulas.',
    keywords: ['ideal weight', 'healthy weight', 'target weight'],
    mode: 'form',
    icon: 'Scale',
  },
  {
    slug: 'water-intake',
    name: 'Water Intake Calculator',
    shortName: 'Water Intake',
    category: 'health',
    description: 'Calculate daily water intake based on weight, activity, and climate.',
    keywords: ['water intake', 'hydration calculator', 'daily water'],
    mode: 'form',
    icon: 'Droplets',
  },
  {
    slug: 'heart-rate',
    name: 'Heart Rate Zone Calculator',
    shortName: 'Heart Rate',
    category: 'health',
    description: 'Calculate your target heart rate zones for optimal training.',
    keywords: ['heart rate zone', 'target heart rate', 'exercise zone'],
    mode: 'form',
    icon: 'HeartPulse',
  },
  {
    slug: 'macro',
    name: 'Macronutrient Calculator',
    shortName: 'Macros',
    category: 'health',
    description: 'Calculate daily protein, carbs, and fat intake based on your goals.',
    keywords: ['macro calculator', 'macronutrient', 'protein carbs fat'],
    mode: 'form',
    icon: 'Apple',
  },
  {
    slug: 'pregnancy',
    name: 'Pregnancy Due Date Calculator',
    shortName: 'Due Date',
    category: 'health',
    description: 'Estimate pregnancy due date and track trimester milestones.',
    keywords: ['pregnancy calculator', 'due date', 'trimester'],
    mode: 'form',
    icon: 'Baby',
  },

  // ═══════════════ DATE & TIME ═══════════════
  {
    slug: 'age',
    name: 'Age Calculator',
    shortName: 'Age',
    category: 'date-time',
    description: 'Calculate exact age in years, months, and days from your birth date.',
    keywords: ['age calculator', 'how old am i', 'date of birth'],
    mode: 'form',
    icon: 'Cake',
  },
  {
    slug: 'date-difference',
    name: 'Date Difference Calculator',
    shortName: 'Date Diff',
    category: 'date-time',
    description: 'Find the exact difference between two dates in days, weeks, months, and years.',
    keywords: ['date difference', 'days between dates', 'date calculator'],
    mode: 'form',
    icon: 'CalendarRange',
  },
  {
    slug: 'time',
    name: 'Time Calculator',
    shortName: 'Time',
    category: 'date-time',
    description: 'Add or subtract hours, minutes, and seconds.',
    keywords: ['time calculator', 'add time', 'subtract time'],
    mode: 'form',
    icon: 'Clock',
  },
  {
    slug: 'countdown',
    name: 'Countdown Calculator',
    shortName: 'Countdown',
    category: 'date-time',
    description: 'Count days until a future event — birthday, holiday, deadline.',
    keywords: ['countdown', 'days until', 'date countdown'],
    mode: 'form',
    icon: 'Timer',
  },

  // ═══════════════ CONVERSION ═══════════════
  {
    slug: 'length',
    name: 'Length Converter',
    shortName: 'Length',
    category: 'conversion',
    description: 'Convert between meters, feet, inches, miles, kilometers, and more.',
    keywords: ['length converter', 'meters to feet', 'distance converter'],
    mode: 'form',
    icon: 'Ruler',
  },
  {
    slug: 'weight',
    name: 'Weight Converter',
    shortName: 'Weight',
    category: 'conversion',
    description: 'Convert between kilograms, pounds, ounces, grams, and stones.',
    keywords: ['weight converter', 'kg to lbs', 'mass converter'],
    mode: 'form',
    icon: 'Weight',
  },
  {
    slug: 'temperature',
    name: 'Temperature Converter',
    shortName: 'Temperature',
    category: 'conversion',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin.',
    keywords: ['temperature converter', 'celsius fahrenheit', 'kelvin'],
    mode: 'form',
    icon: 'Thermometer',
  },
  {
    slug: 'speed',
    name: 'Speed Converter',
    shortName: 'Speed',
    category: 'conversion',
    description: 'Convert between km/h, mph, m/s, knots, and more.',
    keywords: ['speed converter', 'kmh to mph', 'velocity'],
    mode: 'form',
    icon: 'Gauge',
  },
  {
    slug: 'data-storage',
    name: 'Data Storage Converter',
    shortName: 'Data',
    category: 'conversion',
    description: 'Convert between bytes, KB, MB, GB, TB, and PB.',
    keywords: ['data converter', 'bytes to gb', 'storage converter'],
    mode: 'form',
    icon: 'HardDrive',
  },
  {
    slug: 'energy',
    name: 'Energy Converter',
    shortName: 'Energy',
    category: 'conversion',
    description: 'Convert between joules, calories, kWh, BTU, and more.',
    keywords: ['energy converter', 'joules to calories', 'kwh'],
    mode: 'form',
    icon: 'Zap',
  },
  {
    slug: 'cooking',
    name: 'Cooking Converter',
    shortName: 'Cooking',
    category: 'conversion',
    description: 'Convert between cups, tablespoons, teaspoons, ml, liters, and ounces.',
    keywords: ['cooking converter', 'cups to ml', 'tablespoon'],
    mode: 'form',
    icon: 'ChefHat',
  },

  // ═══════════════ EVERYDAY ═══════════════
  {
    slug: 'gpa',
    name: 'GPA Calculator',
    shortName: 'GPA',
    category: 'everyday',
    description: 'Calculate your Grade Point Average from courses and credits.',
    keywords: ['gpa calculator', 'grade calculator', 'college gpa'],
    mode: 'form',
    icon: 'GraduationCap',
  },
  {
    slug: 'random-number',
    name: 'Random Number Generator',
    shortName: 'Random',
    category: 'everyday',
    description: 'Generate random numbers within a specified range.',
    keywords: ['random number generator', 'rng', 'random'],
    mode: 'retro',
    icon: 'Dices',
  },
  {
    slug: 'password',
    name: 'Password Generator',
    shortName: 'Password',
    category: 'everyday',
    description: 'Generate strong, secure passwords with customizable options.',
    keywords: ['password generator', 'secure password', 'random password'],
    mode: 'form',
    icon: 'KeyRound',
  },
  {
    slug: 'word-counter',
    name: 'Word & Character Counter',
    shortName: 'Word Count',
    category: 'everyday',
    description: 'Count words, characters, sentences, and paragraphs in your text.',
    keywords: ['word counter', 'character counter', 'text counter'],
    mode: 'form',
    icon: 'Type',
  },
  {
    slug: 'color',
    name: 'Color Converter',
    shortName: 'Color',
    category: 'everyday',
    description: 'Convert between HEX, RGB, and HSL color formats with live preview.',
    keywords: ['color converter', 'hex to rgb', 'color picker'],
    mode: 'form',
    icon: 'Palette',
  },
]

export function getCalculatorBySlug(slug: string): CalculatorEntry | undefined {
  return calculators.find((c) => c.slug === slug)
}

export function getCalculatorsByCategory(category: CalculatorCategory): CalculatorEntry[] {
  return calculators.filter((c) => c.category === category)
}

export function getAllSlugs(): string[] {
  return calculators.map((c) => c.slug)
}
