'use client'

import dynamic from 'next/dynamic'
import React from 'react'

// Dynamic imports for all calculator components — code-split per calculator
const calculatorComponents: Record<string, React.ComponentType> = {
  // ═══════════════ MATH (25) ═══════════════
  'basic': dynamic(() => import('@/components/calculators/math/BasicCalculator')),
  'scientific': dynamic(() => import('@/components/calculators/math/ScientificCalculator')),
  'percentage': dynamic(() => import('@/components/calculators/math/PercentageCalculator')),
  'fraction': dynamic(() => import('@/components/calculators/math/FractionCalculator')),
  'area': dynamic(() => import('@/components/calculators/math/AreaCalculator')),
  'volume': dynamic(() => import('@/components/calculators/math/VolumeCalculator')),
  'quadratic': dynamic(() => import('@/components/calculators/math/QuadraticCalculator')),
  'statistics': dynamic(() => import('@/components/calculators/math/StatisticsCalculator')),
  'gcd-lcm': dynamic(() => import('@/components/calculators/math/GcdLcmCalculator')),
  'number-base': dynamic(() => import('@/components/calculators/math/NumberBaseConverter')),
  'exponent': dynamic(() => import('@/components/calculators/math/ExponentCalculator')),
  'permutation-combination': dynamic(() => import('@/components/calculators/math/PermutationCombinationCalculator')),
  'ratio': dynamic(() => import('@/components/calculators/math/RatioCalculator')),
  'logarithm': dynamic(() => import('@/components/calculators/math/LogarithmCalculator')),
  'pythagorean': dynamic(() => import('@/components/calculators/math/PythagoreanCalculator')),
  'circle': dynamic(() => import('@/components/calculators/math/CircleCalculator')),
  'triangle': dynamic(() => import('@/components/calculators/math/TriangleCalculator')),
  'prime-factorization': dynamic(() => import('@/components/calculators/math/PrimeFactorizationCalculator')),
  'rounding': dynamic(() => import('@/components/calculators/math/RoundingCalculator')),
  'scientific-notation': dynamic(() => import('@/components/calculators/math/ScientificNotationCalculator')),
  'standard-deviation': dynamic(() => import('@/components/calculators/math/StandardDeviationCalculator')),
  'mean-median-mode': dynamic(() => import('@/components/calculators/math/MeanMedianModeCalculator')),
  'z-score': dynamic(() => import('@/components/calculators/math/ZScoreCalculator')),
  'confidence-interval': dynamic(() => import('@/components/calculators/math/ConfidenceIntervalCalculator')),
  'probability': dynamic(() => import('@/components/calculators/math/ProbabilityCalculator')),

  // ═══════════════ FINANCE (30) ═══════════════
  'loan-emi': dynamic(() => import('@/components/calculators/finance/LoanEmiCalculator')),
  'compound-interest': dynamic(() => import('@/components/calculators/finance/CompoundInterestCalculator')),
  'simple-interest': dynamic(() => import('@/components/calculators/finance/SimpleInterestCalculator')),
  'sip': dynamic(() => import('@/components/calculators/finance/SipCalculator')),
  'tip': dynamic(() => import('@/components/calculators/finance/TipCalculator')),
  'discount': dynamic(() => import('@/components/calculators/finance/DiscountCalculator')),
  'profit-margin': dynamic(() => import('@/components/calculators/finance/ProfitMarginCalculator')),
  'roi': dynamic(() => import('@/components/calculators/finance/RoiCalculator')),
  'salary': dynamic(() => import('@/components/calculators/finance/SalaryCalculator')),
  'mortgage': dynamic(() => import('@/components/calculators/finance/MortgageCalculator')),
  'inflation': dynamic(() => import('@/components/calculators/finance/InflationCalculator')),
  'break-even': dynamic(() => import('@/components/calculators/finance/BreakEvenCalculator')),
  'savings-goal': dynamic(() => import('@/components/calculators/finance/SavingsGoalCalculator')),
  'currency': dynamic(() => import('@/components/calculators/finance/CurrencyConverter')),
  'auto-loan': dynamic(() => import('@/components/calculators/finance/AutoLoanCalculator')),
  'credit-card-payoff': dynamic(() => import('@/components/calculators/finance/CreditCardPayoffCalculator')),
  'debt-to-income': dynamic(() => import('@/components/calculators/finance/DebtToIncomeCalculator')),
  'refinance': dynamic(() => import('@/components/calculators/finance/RefinanceCalculator')),
  'rent-vs-buy': dynamic(() => import('@/components/calculators/finance/RentVsBuyCalculator')),
  'present-value': dynamic(() => import('@/components/calculators/finance/PresentValueCalculator')),
  'future-value': dynamic(() => import('@/components/calculators/finance/FutureValueCalculator')),
  'annuity': dynamic(() => import('@/components/calculators/finance/AnnuityCalculator')),
  'retirement': dynamic(() => import('@/components/calculators/finance/RetirementCalculator')),
  '401k': dynamic(() => import('@/components/calculators/finance/FourOhOneKCalculator')),
  'sales-tax': dynamic(() => import('@/components/calculators/finance/SalesTaxCalculator')),
  'commission': dynamic(() => import('@/components/calculators/finance/CommissionCalculator')),
  'apr': dynamic(() => import('@/components/calculators/finance/AprCalculator')),
  'depreciation': dynamic(() => import('@/components/calculators/finance/DepreciationCalculator')),
  'gold-price': dynamic(() => import('@/components/calculators/finance/GoldPriceCalculator')),
  'crypto-converter': dynamic(() => import('@/components/calculators/finance/CryptoConverter')),

  // ═══════════════ HEALTH (22) ═══════════════
  'bmi': dynamic(() => import('@/components/calculators/health/BmiCalculator')),
  'calorie': dynamic(() => import('@/components/calculators/health/CalorieCalculator')),
  'body-fat': dynamic(() => import('@/components/calculators/health/BodyFatCalculator')),
  'ideal-weight': dynamic(() => import('@/components/calculators/health/IdealWeightCalculator')),
  'water-intake': dynamic(() => import('@/components/calculators/health/WaterIntakeCalculator')),
  'heart-rate': dynamic(() => import('@/components/calculators/health/HeartRateCalculator')),
  'macro': dynamic(() => import('@/components/calculators/health/MacroCalculator')),
  'pregnancy': dynamic(() => import('@/components/calculators/health/PregnancyCalculator')),
  'bmr': dynamic(() => import('@/components/calculators/health/BmrCalculator')),
  'tdee': dynamic(() => import('@/components/calculators/health/TdeeCalculator')),
  'one-rep-max': dynamic(() => import('@/components/calculators/health/OneRepMaxCalculator')),
  'ovulation': dynamic(() => import('@/components/calculators/health/OvulationCalculator')),
  'bac': dynamic(() => import('@/components/calculators/health/BacCalculator')),
  'pace': dynamic(() => import('@/components/calculators/health/PaceCalculator')),
  'protein': dynamic(() => import('@/components/calculators/health/ProteinCalculator')),
  'carbohydrate': dynamic(() => import('@/components/calculators/health/CarbohydrateCalculator')),
  'lean-body-mass': dynamic(() => import('@/components/calculators/health/LeanBodyMassCalculator')),
  'body-surface-area': dynamic(() => import('@/components/calculators/health/BodySurfaceAreaCalculator')),
  'gfr': dynamic(() => import('@/components/calculators/health/GfrCalculator')),
  'pregnancy-weight-gain': dynamic(() => import('@/components/calculators/health/PregnancyWeightGainCalculator')),
  'conception': dynamic(() => import('@/components/calculators/health/ConceptionCalculator')),
  'period': dynamic(() => import('@/components/calculators/health/PeriodCalculator')),

  // ═══════════════ DATE & TIME (12) ═══════════════
  'age': dynamic(() => import('@/components/calculators/datetime/AgeCalculator')),
  'date-difference': dynamic(() => import('@/components/calculators/datetime/DateDifferenceCalculator')),
  'time': dynamic(() => import('@/components/calculators/datetime/TimeCalculator')),
  'countdown': dynamic(() => import('@/components/calculators/datetime/CountdownCalculator')),
  'day-of-week': dynamic(() => import('@/components/calculators/datetime/DayOfWeekCalculator')),
  'time-zone': dynamic(() => import('@/components/calculators/datetime/TimeZoneCalculator')),
  'time-duration': dynamic(() => import('@/components/calculators/datetime/TimeDurationCalculator')),
  'hours': dynamic(() => import('@/components/calculators/datetime/HoursCalculator')),
  'date-calculator': dynamic(() => import('@/components/calculators/datetime/DateCalculator')),
  'day-counter': dynamic(() => import('@/components/calculators/datetime/DayCounter')),
  'sleep': dynamic(() => import('@/components/calculators/datetime/SleepCalculator')),
  'time-card': dynamic(() => import('@/components/calculators/datetime/TimeCardCalculator')),

  // ═══════════════ CONVERSION (12) ═══════════════
  'length': dynamic(() => import('@/components/calculators/conversion/LengthConverter')),
  'weight': dynamic(() => import('@/components/calculators/conversion/WeightConverter')),
  'temperature': dynamic(() => import('@/components/calculators/conversion/TemperatureConverter')),
  'speed': dynamic(() => import('@/components/calculators/conversion/SpeedConverter')),
  'data-storage': dynamic(() => import('@/components/calculators/conversion/DataStorageConverter')),
  'energy': dynamic(() => import('@/components/calculators/conversion/EnergyConverter')),
  'cooking': dynamic(() => import('@/components/calculators/conversion/CookingConverter')),
  'pressure': dynamic(() => import('@/components/calculators/conversion/PressureConverter')),
  'angle': dynamic(() => import('@/components/calculators/conversion/AngleConverter')),
  'power': dynamic(() => import('@/components/calculators/conversion/PowerConverter')),
  'fuel': dynamic(() => import('@/components/calculators/conversion/FuelConverter')),
  'roman-numeral': dynamic(() => import('@/components/calculators/conversion/RomanNumeralConverter')),

  // ═══════════════ EVERYDAY (12) ═══════════════
  'gpa': dynamic(() => import('@/components/calculators/everyday/GpaCalculator')),
  'random-number': dynamic(() => import('@/components/calculators/everyday/RandomNumberGenerator')),
  'password': dynamic(() => import('@/components/calculators/everyday/PasswordGenerator')),
  'word-counter': dynamic(() => import('@/components/calculators/everyday/WordCounter')),
  'color': dynamic(() => import('@/components/calculators/everyday/ColorConverter')),
  'grade': dynamic(() => import('@/components/calculators/everyday/GradeCalculator')),
  'url-encode': dynamic(() => import('@/components/calculators/everyday/UrlEncodeCalculator')),
  'base64': dynamic(() => import('@/components/calculators/everyday/Base64Calculator')),
  'ip-subnet': dynamic(() => import('@/components/calculators/everyday/IpSubnetCalculator')),
  'height': dynamic(() => import('@/components/calculators/everyday/HeightConverter')),
  'shoe-size': dynamic(() => import('@/components/calculators/everyday/ShoeSizeConverter')),
  'love': dynamic(() => import('@/components/calculators/everyday/LoveCalculator')),

  // ═══════════════ ISLAMIC (8) ═══════════════
  'zakat': dynamic(() => import('@/components/calculators/islamic/ZakatCalculator')),
  'prayer-times': dynamic(() => import('@/components/calculators/islamic/PrayerTimesCalculator')),
  'hijri-date': dynamic(() => import('@/components/calculators/islamic/HijriDateCalculator')),
  'inheritance': dynamic(() => import('@/components/calculators/islamic/InheritanceCalculator')),
  'qibla': dynamic(() => import('@/components/calculators/islamic/QiblaCalculator')),
  'ramadan': dynamic(() => import('@/components/calculators/islamic/RamadanCalculator')),
  'tahajjud': dynamic(() => import('@/components/calculators/islamic/TahajjudCalculator')),
  'hajj-dates': dynamic(() => import('@/components/calculators/islamic/HajjDatesCalculator')),

  // ═══════════════ CONSTRUCTION (10) ═══════════════
  'concrete': dynamic(() => import('@/components/calculators/construction/ConcreteCalculator')),
  'tile': dynamic(() => import('@/components/calculators/construction/TileCalculator')),
  'gravel': dynamic(() => import('@/components/calculators/construction/GravelCalculator')),
  'mulch': dynamic(() => import('@/components/calculators/construction/MulchCalculator')),
  'roofing': dynamic(() => import('@/components/calculators/construction/RoofingCalculator')),
  'stair': dynamic(() => import('@/components/calculators/construction/StairCalculator')),
  'paint': dynamic(() => import('@/components/calculators/construction/PaintCalculator')),
  'square-footage': dynamic(() => import('@/components/calculators/construction/SquareFootageCalculator')),
  'drywall': dynamic(() => import('@/components/calculators/construction/DrywallCalculator')),
  'flooring': dynamic(() => import('@/components/calculators/construction/FlooringCalculator')),

  // ═══════════════ ENGINEERING (8) ═══════════════
  'ohms-law': dynamic(() => import('@/components/calculators/engineering/OhmsLawCalculator')),
  'resistor': dynamic(() => import('@/components/calculators/engineering/ResistorCalculator')),
  'bandwidth': dynamic(() => import('@/components/calculators/engineering/BandwidthCalculator')),
  'voltage-drop': dynamic(() => import('@/components/calculators/engineering/VoltageDropCalculator')),
  'horsepower': dynamic(() => import('@/components/calculators/engineering/HorsepowerCalculator')),
  'density': dynamic(() => import('@/components/calculators/engineering/DensityCalculator')),
  'molarity': dynamic(() => import('@/components/calculators/engineering/MolarityCalculator')),
  'tip-speed': dynamic(() => import('@/components/calculators/engineering/TipSpeedCalculator')),

  // ═══════════════ MISC / OTHER (12) ═══════════════
  'dice-roller': dynamic(() => import('@/components/calculators/misc/DiceRoller')),
  'fuel-cost': dynamic(() => import('@/components/calculators/misc/FuelCostCalculator')),
  'btu': dynamic(() => import('@/components/calculators/misc/BtuCalculator')),
  'wind-chill': dynamic(() => import('@/components/calculators/misc/WindChillCalculator')),
  'dew-point': dynamic(() => import('@/components/calculators/misc/DewPointCalculator')),
  'heat-index': dynamic(() => import('@/components/calculators/misc/HeatIndexCalculator')),
  'golf-handicap': dynamic(() => import('@/components/calculators/misc/GolfHandicapCalculator')),
  'tire-size': dynamic(() => import('@/components/calculators/misc/TireSizeCalculator')),
  'mileage': dynamic(() => import('@/components/calculators/misc/MileageCalculator')),
  'tip-splitter': dynamic(() => import('@/components/calculators/misc/BillSplitter')),
  'molecular-weight': dynamic(() => import('@/components/calculators/misc/MolecularWeightCalculator')),
  'weather': dynamic(() => import('@/components/calculators/misc/WeatherCalculator')),

  // ═══════════════ GEOMETRY (13) ═══════════════
  'polygon-area': dynamic(() => import('@/components/calculators/geometry/PolygonAreaCalculator')),
  'ellipse': dynamic(() => import('@/components/calculators/geometry/EllipseCalculator')),
  'sphere': dynamic(() => import('@/components/calculators/geometry/SphereCalculator')),
  'cylinder-geo': dynamic(() => import('@/components/calculators/geometry/CylinderGeoCalculator')),
  'cone': dynamic(() => import('@/components/calculators/geometry/ConeCalculator')),
  'pyramid': dynamic(() => import('@/components/calculators/geometry/PyramidCalculator')),
  'parallelogram': dynamic(() => import('@/components/calculators/geometry/ParallelogramCalculator')),
  'trapezoid': dynamic(() => import('@/components/calculators/geometry/TrapezoidCalculator')),
  'sector': dynamic(() => import('@/components/calculators/geometry/SectorCalculator')),
  'segment': dynamic(() => import('@/components/calculators/geometry/SegmentCalculator')),
  'distance-2d': dynamic(() => import('@/components/calculators/geometry/Distance2dCalculator')),
  'distance-3d': dynamic(() => import('@/components/calculators/geometry/Distance3dCalculator')),
  'midpoint': dynamic(() => import('@/components/calculators/geometry/MidpointCalculator')),

  // ═══════════════ STATISTICS (13) ═══════════════
  'correlation': dynamic(() => import('@/components/calculators/statistics/CorrelationCalculator')),
  'regression': dynamic(() => import('@/components/calculators/statistics/RegressionCalculator')),
  'binomial': dynamic(() => import('@/components/calculators/statistics/BinomialCalculator')),
  'normal-distribution': dynamic(() => import('@/components/calculators/statistics/NormalDistributionCalculator')),
  'poisson': dynamic(() => import('@/components/calculators/statistics/PoissonCalculator')),
  'chi-square': dynamic(() => import('@/components/calculators/statistics/ChiSquareCalculator')),
  't-test': dynamic(() => import('@/components/calculators/statistics/TTestCalculator')),
  'anova': dynamic(() => import('@/components/calculators/statistics/AnovaCalculator')),
  'outlier': dynamic(() => import('@/components/calculators/statistics/OutlierCalculator')),
  'percentile': dynamic(() => import('@/components/calculators/statistics/PercentileCalculator')),
  'effect-size': dynamic(() => import('@/components/calculators/statistics/EffectSizeCalculator')),
  'sampling': dynamic(() => import('@/components/calculators/statistics/SamplingCalculator')),
  'histogram': dynamic(() => import('@/components/calculators/statistics/HistogramCalculator')),

  // ═══════════════ TRIGONOMETRY (13) ═══════════════
  'sin-cos-tan': dynamic(() => import('@/components/calculators/trigonometry/SinCosTanCalculator')),
  'inverse-trig': dynamic(() => import('@/components/calculators/trigonometry/InverseTrigCalculator')),
  'unit-circle': dynamic(() => import('@/components/calculators/trigonometry/UnitCircleCalculator')),
  'law-of-sines': dynamic(() => import('@/components/calculators/trigonometry/LawOfSinesCalculator')),
  'law-of-cosines': dynamic(() => import('@/components/calculators/trigonometry/LawOfCosinesCalculator')),
  'trig-identities': dynamic(() => import('@/components/calculators/trigonometry/TrigIdentitiesCalculator')),
  'polar-rectangular': dynamic(() => import('@/components/calculators/trigonometry/PolarRectangularCalculator')),
  'deg-rad': dynamic(() => import('@/components/calculators/trigonometry/DegRadCalculator')),
  'trig-graph': dynamic(() => import('@/components/calculators/trigonometry/TrigGraphCalculator')),
  'reference-angle': dynamic(() => import('@/components/calculators/trigonometry/ReferenceAngleCalculator')),
  'coterminal': dynamic(() => import('@/components/calculators/trigonometry/CoterminalCalculator')),
  'trig-equation': dynamic(() => import('@/components/calculators/trigonometry/TrigEquationCalculator')),
  'hyperbolic': dynamic(() => import('@/components/calculators/trigonometry/HyperbolicCalculator')),

  // ═══════════════ PHYSICS (23) ═══════════════
  'newton-force': dynamic(() => import('@/components/calculators/physics/NewtonForceCalculator')),
  'kinetic-energy': dynamic(() => import('@/components/calculators/physics/KineticEnergyCalculator')),
  'potential-energy': dynamic(() => import('@/components/calculators/physics/PotentialEnergyCalculator')),
  'velocity': dynamic(() => import('@/components/calculators/physics/VelocityCalculator')),
  'acceleration': dynamic(() => import('@/components/calculators/physics/AccelerationCalculator')),
  'momentum': dynamic(() => import('@/components/calculators/physics/MomentumCalculator')),
  'free-fall': dynamic(() => import('@/components/calculators/physics/FreeFallCalculator')),
  'work': dynamic(() => import('@/components/calculators/physics/WorkCalculator')),
  'power-physics': dynamic(() => import('@/components/calculators/physics/PowerCalculator')),
  'density-physics': dynamic(() => import('@/components/calculators/physics/DensityPhysicsCalculator')),
  'pressure-physics': dynamic(() => import('@/components/calculators/physics/PressureCalculator')),
  'wave-speed': dynamic(() => import('@/components/calculators/physics/WaveSpeedCalculator')),
  'spring-force': dynamic(() => import('@/components/calculators/physics/SpringForceCalculator')),
  'centripetal-force': dynamic(() => import('@/components/calculators/physics/CentripetalForceCalculator')),
  'projectile-range': dynamic(() => import('@/components/calculators/physics/ProjectileRangeCalculator')),
  'gravitational-force': dynamic(() => import('@/components/calculators/physics/GravitationalForceCalculator')),
  'specific-heat': dynamic(() => import('@/components/calculators/physics/SpecificHeatCalculator')),
  'pendulum-period': dynamic(() => import('@/components/calculators/physics/PendulumPeriodCalculator')),
  'friction-force': dynamic(() => import('@/components/calculators/physics/FrictionForceCalculator')),
  'electric-field': dynamic(() => import('@/components/calculators/physics/ElectricFieldCalculator')),
  'capacitance': dynamic(() => import('@/components/calculators/physics/CapacitanceCalculator')),
  'sound-frequency': dynamic(() => import('@/components/calculators/physics/SoundFrequencyCalculator')),
  'lens-magnification': dynamic(() => import('@/components/calculators/physics/LensMagnificationCalculator')),
  'thermal-expansion': dynamic(() => import('@/components/calculators/physics/ThermalExpansionCalculator')),
  'coulombs-law': dynamic(() => import('@/components/calculators/physics/CoulombsLawCalculator')),
  'magnetic-force': dynamic(() => import('@/components/calculators/physics/MagneticForceCalculator')),
  'impulse': dynamic(() => import('@/components/calculators/physics/ImpulseCalculator')),
  'orbital-velocity': dynamic(() => import('@/components/calculators/physics/OrbitalVelocityCalculator')),
  'torque': dynamic(() => import('@/components/calculators/physics/TorqueCalculator')),

  // ═══════════════ CHEMISTRY (20) ═══════════════
  'molar-mass': dynamic(() => import('@/components/calculators/chemistry/MolarMassCalculator')),
  'ph': dynamic(() => import('@/components/calculators/chemistry/PHCalculator')),
  'moles': dynamic(() => import('@/components/calculators/chemistry/MolesCalculator')),
  'dilution': dynamic(() => import('@/components/calculators/chemistry/DilutionCalculator')),
  'gas-pressure': dynamic(() => import('@/components/calculators/chemistry/GasPressureCalculator')),
  'mass-percent': dynamic(() => import('@/components/calculators/chemistry/MassPercentCalculator')),
  'limiting-reagent': dynamic(() => import('@/components/calculators/chemistry/LimitingReagentCalculator')),
  'yield': dynamic(() => import('@/components/calculators/chemistry/YieldCalculator')),
  'atom-count': dynamic(() => import('@/components/calculators/chemistry/AtomCountCalculator')),
  'neutralization': dynamic(() => import('@/components/calculators/chemistry/NeutralizationCalculator')),
  'bohr-radius': dynamic(() => import('@/components/calculators/chemistry/BohrRadiusCalculator')),
  'molarity-chem': dynamic(() => import('@/components/calculators/chemistry/MolarityChemCalculator')),
  'half-life': dynamic(() => import('@/components/calculators/chemistry/HalfLifeCalculator')),
  'empirical-formula': dynamic(() => import('@/components/calculators/chemistry/EmpiricalFormulaCalculator')),
  'avogadros-number': dynamic(() => import('@/components/calculators/chemistry/AvogadrosNumberCalculator')),
  'molality': dynamic(() => import('@/components/calculators/chemistry/MolalityCalculator')),
  'heat-of-reaction': dynamic(() => import('@/components/calculators/chemistry/HeatOfReactionCalculator')),
  'electron-config': dynamic(() => import('@/components/calculators/chemistry/ElectronConfigCalculator')),
  'solution-mix': dynamic(() => import('@/components/calculators/chemistry/SolutionMixCalculator')),
  'poh': dynamic(() => import('@/components/calculators/chemistry/PohCalculator')),
  'bond-energy': dynamic(() => import('@/components/calculators/chemistry/BondEnergyCalculator')),

  // ═══════════════ ASTRONOMY (12) ═══════════════
  'light-year': dynamic(() => import('@/components/calculators/astronomy/LightYearCalculator')),
  'escape-velocity': dynamic(() => import('@/components/calculators/astronomy/EscapeVelocityCalculator')),
  'schwarzschild-radius': dynamic(() => import('@/components/calculators/astronomy/SchwarzschildRadiusCalculator')),
  'hubble-law': dynamic(() => import('@/components/calculators/astronomy/HubbleLawCalculator')),
  'stellar-luminosity': dynamic(() => import('@/components/calculators/astronomy/StellarLuminosityCalculator')),
  'planetary-orbit': dynamic(() => import('@/components/calculators/astronomy/PlanetaryOrbitCalculator')),
  'redshift': dynamic(() => import('@/components/calculators/astronomy/RedshiftCalculator')),
  'angular-diameter': dynamic(() => import('@/components/calculators/astronomy/AngularDiameterCalculator')),
  'tidal-force': dynamic(() => import('@/components/calculators/astronomy/TidalForceCalculator')),
  'stefan-boltzmann': dynamic(() => import('@/components/calculators/astronomy/StefanBoltzmannCalculator')),
  'wien-displacement': dynamic(() => import('@/components/calculators/astronomy/WienDisplacementCalculator')),
  'parsec-converter': dynamic(() => import('@/components/calculators/astronomy/ParsecConverter')),

  // ═══════════════ AGRICULTURE (11) ═══════════════
  'fertilizer': dynamic(() => import('@/components/calculators/agriculture/FertilizerCalculator')),
  'irrigation': dynamic(() => import('@/components/calculators/agriculture/IrrigationCalculator')),
  'crop-yield': dynamic(() => import('@/components/calculators/agriculture/CropYieldCalculator')),
  'seed-rate': dynamic(() => import('@/components/calculators/agriculture/SeedRateCalculator')),
  'soil-area': dynamic(() => import('@/components/calculators/agriculture/SoilAreaCalculator')),
  'compost': dynamic(() => import('@/components/calculators/agriculture/CompostCalculator')),
  'hay-yield': dynamic(() => import('@/components/calculators/agriculture/HayYieldCalculator')),
  'animal-feed': dynamic(() => import('@/components/calculators/agriculture/AnimalFeedCalculator')),
  'greenhouse-area': dynamic(() => import('@/components/calculators/agriculture/GreenhouseAreaCalculator')),
  'rainfall-volume': dynamic(() => import('@/components/calculators/agriculture/RainfallVolumeCalculator')),
  'pesticide': dynamic(() => import('@/components/calculators/agriculture/PesticideCalculator')),

  // ═══════════════ PHOTOGRAPHY (10) ═══════════════
  'depth-of-field': dynamic(() => import('@/components/calculators/photography/DepthOfFieldCalculator')),
  'exposure': dynamic(() => import('@/components/calculators/photography/ExposureCalculator')),
  'hyperfocal': dynamic(() => import('@/components/calculators/photography/HyperfocalDistanceCalculator')),
  'crop-factor': dynamic(() => import('@/components/calculators/photography/CropFactorCalculator')),
  'print-size': dynamic(() => import('@/components/calculators/photography/PrintSizeCalculator')),
  'aspect-ratio': dynamic(() => import('@/components/calculators/photography/AspectRatioCalculator')),
  'megapixel': dynamic(() => import('@/components/calculators/photography/MegapixelCalculator')),
  'nd-filter': dynamic(() => import('@/components/calculators/photography/NDFilterCalculator')),
  'time-lapse': dynamic(() => import('@/components/calculators/photography/TimeLapseCalculator')),
  'field-of-view': dynamic(() => import('@/components/calculators/photography/FieldOfViewCalculator')),

  // ═══════════════ ENVIRONMENT (10) ═══════════════
  'carbon-footprint': dynamic(() => import('@/components/calculators/environment/CarbonFootprintCalculator')),
  'solar-panel': dynamic(() => import('@/components/calculators/environment/SolarPanelCalculator')),
  'water-usage': dynamic(() => import('@/components/calculators/environment/WaterUsageCalculator')),
  'tree-planting': dynamic(() => import('@/components/calculators/environment/TreePlantingCalculator')),
  'wind-energy': dynamic(() => import('@/components/calculators/environment/WindEnergyCalculator')),
  'energy-savings': dynamic(() => import('@/components/calculators/environment/EnergySavingsCalculator')),
  'recycling': dynamic(() => import('@/components/calculators/environment/RecyclingCalculator')),
  'ev-savings': dynamic(() => import('@/components/calculators/environment/EVSavingsCalculator')),
  'air-quality': dynamic(() => import('@/components/calculators/environment/AirQualityCalculator')),
  'ecological-footprint': dynamic(() => import('@/components/calculators/environment/EcologicalFootprintCalculator')),

  // ═══════════════ REAL ESTATE (10) ═══════════════
  'rental-yield': dynamic(() => import('@/components/calculators/real-estate/RentalYieldCalculator')),
  'cap-rate': dynamic(() => import('@/components/calculators/real-estate/CapRateCalculator')),
  'closing-cost': dynamic(() => import('@/components/calculators/real-estate/ClosingCostCalculator')),
  'property-tax-re': dynamic(() => import('@/components/calculators/real-estate/PropertyTaxCalculator')),
  'cash-on-cash': dynamic(() => import('@/components/calculators/real-estate/CashOnCashCalculator')),
  'dscr': dynamic(() => import('@/components/calculators/real-estate/DSCRCalculator')),
  'stamp-duty': dynamic(() => import('@/components/calculators/real-estate/StampDutyCalculator')),
  'ltv': dynamic(() => import('@/components/calculators/real-estate/LTVCalculator')),
  'home-appreciation': dynamic(() => import('@/components/calculators/real-estate/HomeAppreciationCalculator')),
  'flip-roi': dynamic(() => import('@/components/calculators/real-estate/FlipROIReCalculator')),

  // ═══════════════ TAX (10) ═══════════════
  'income-tax': dynamic(() => import('@/components/calculators/tax/IncomeTaxCalculator')),
  'capital-gains-tax': dynamic(() => import('@/components/calculators/tax/CapitalGainsTaxCalculator')),
  'vat': dynamic(() => import('@/components/calculators/tax/VATCalculator')),
  'tax-refund': dynamic(() => import('@/components/calculators/tax/TaxRefundCalculator')),
  'self-employed-tax': dynamic(() => import('@/components/calculators/tax/SelfEmployedTaxCalculator')),
  'marginal-tax': dynamic(() => import('@/components/calculators/tax/MarginalTaxCalculator')),
  'estate-tax': dynamic(() => import('@/components/calculators/tax/EstateTaxCalculator')),
  'payroll-tax': dynamic(() => import('@/components/calculators/tax/PayrollTaxCalculator')),
  'dividend-tax': dynamic(() => import('@/components/calculators/tax/DividendTaxCalculator')),
  'property-tax-deduction': dynamic(() => import('@/components/calculators/tax/PropertyTaxDeductionCalculator')),

  // ═══════════════ AUTOMOTIVE (11) ═══════════════
  'fuel-cost-trip': dynamic(() => import('@/components/calculators/automotive/FuelCostTripCalculator')),
  'car-loan': dynamic(() => import('@/components/calculators/automotive/CarLoanCalculator')),
  'tire-pressure': dynamic(() => import('@/components/calculators/automotive/TirePressureCalculator')),
  'car-depreciation': dynamic(() => import('@/components/calculators/automotive/CarDepreciationCalculator')),
  'brake-distance': dynamic(() => import('@/components/calculators/automotive/BrakeDistanceCalculator')),
  'engine-displacement': dynamic(() => import('@/components/calculators/automotive/EngineDisplacementCalculator')),
  'ev-range': dynamic(() => import('@/components/calculators/automotive/EVRangeCalculator')),
  'maintenance-cost': dynamic(() => import('@/components/calculators/automotive/MaintenanceCostCalculator')),
  'gear-ratio': dynamic(() => import('@/components/calculators/automotive/GearRatioCalculator')),
  'insurance-premium': dynamic(() => import('@/components/calculators/automotive/InsurancePremiumCalculator')),
  'cost-per-mile': dynamic(() => import('@/components/calculators/automotive/CostPerMileCalculator')),

  // ═══════════════ SPORTS & FITNESS (12) ═══════════════
  'calorie-burn': dynamic(() => import('@/components/calculators/sports/CalorieBurnCalculator')),
  'running-pace-sports': dynamic(() => import('@/components/calculators/sports/RunningPaceSportsCalculator')),
  'hydration-sports': dynamic(() => import('@/components/calculators/sports/WaterIntakeSportsCalculator')),
  'vo2-max': dynamic(() => import('@/components/calculators/sports/VO2MaxCalculator')),
  'max-heart-rate': dynamic(() => import('@/components/calculators/sports/MaxHeartRateCalculator')),
  'bench-press-ratio': dynamic(() => import('@/components/calculators/sports/BenchPressRatioCalculator')),
  'sprint-speed': dynamic(() => import('@/components/calculators/sports/SprintSpeedCalculator')),
  'swimming-pace': dynamic(() => import('@/components/calculators/sports/SwimmingPaceCalculator')),
  'cycling-power': dynamic(() => import('@/components/calculators/sports/CyclingPowerCalculator')),
  'vertical-jump': dynamic(() => import('@/components/calculators/sports/VerticalJumpCalculator')),
  'wilks-score': dynamic(() => import('@/components/calculators/sports/WilksScoreCalculator')),
  'training-load': dynamic(() => import('@/components/calculators/sports/TrainingLoadCalculator')),

  // ═══════════════ COOKING & FOOD (12) ═══════════════
  'recipe-scaler': dynamic(() => import('@/components/calculators/cooking/RecipeScalerCalculator')),
  'oven-temp': dynamic(() => import('@/components/calculators/cooking/OvenTempCalculator')),
  'meat-thermometer': dynamic(() => import('@/components/calculators/cooking/MeatThermometerCalculator')),
  'flour-weight': dynamic(() => import('@/components/calculators/cooking/FlourWeightCalculator')),
  'sugar-converter-cooking': dynamic(() => import('@/components/calculators/cooking/SugarConverterCooking')),
  'butter-converter': dynamic(() => import('@/components/calculators/cooking/ButterConverterCalculator')),
  'cooking-time': dynamic(() => import('@/components/calculators/cooking/CookingTimeCalculator')),
  'pizza-dough': dynamic(() => import('@/components/calculators/cooking/PizzaDoughCalculator')),
  'bread-hydration': dynamic(() => import('@/components/calculators/cooking/BreadHydrationCalculator')),
  'coffee-ratio': dynamic(() => import('@/components/calculators/cooking/CoffeeRatioCalculator')),
  'brine': dynamic(() => import('@/components/calculators/cooking/BrineCalculator')),
  'alcohol-cooking': dynamic(() => import('@/components/calculators/cooking/AlcoholCookingCalculator')),

  // ═══════════════ EDUCATION (10) ═══════════════
  'gpa-semester': dynamic(() => import('@/components/calculators/education/GpaSemesterCalculator')),
  'study-time': dynamic(() => import('@/components/calculators/education/StudyTimeCalculator')),
  'grade-curve': dynamic(() => import('@/components/calculators/education/GradeCurveCalculator')),
  'attendance': dynamic(() => import('@/components/calculators/education/AttendanceCalculator')),
  'exam-score': dynamic(() => import('@/components/calculators/education/ExamScoreCalculator')),
  'reading-speed': dynamic(() => import('@/components/calculators/education/ReadingSpeedCalculator')),
  'credit-hours': dynamic(() => import('@/components/calculators/education/CreditHoursCalculator')),
  'scholarship-eligibility': dynamic(() => import('@/components/calculators/education/ScholarshipEligibilityCalculator')),
  'weighted-gpa': dynamic(() => import('@/components/calculators/education/GradePointAverageCalculator')),
  'test-percentile': dynamic(() => import('@/components/calculators/education/TestScorePercentileCalculator')),

  // ═══════════════ BUSINESS (10) ═══════════════
  'markup': dynamic(() => import('@/components/calculators/business/MarkupCalculator')),
  'inventory-turnover': dynamic(() => import('@/components/calculators/business/InventoryTurnoverCalculator')),
  'cash-flow': dynamic(() => import('@/components/calculators/business/CashFlowCalculator')),
  'npv': dynamic(() => import('@/components/calculators/business/NPVCalculator')),
  'irr': dynamic(() => import('@/components/calculators/business/IRRCalculator')),
  'ebitda': dynamic(() => import('@/components/calculators/business/EBITDACalculator')),
  'cac': dynamic(() => import('@/components/calculators/business/CustomerAcquisitionCostCalculator')),
  'ltv-business': dynamic(() => import('@/components/calculators/business/LifetimeValueCalculator')),
  'churn-rate': dynamic(() => import('@/components/calculators/business/ChurnRateCalculator')),
  'gross-margin-biz': dynamic(() => import('@/components/calculators/business/GrossMarginCalculator')),

  // ═══════════════ SCIENCE (10) ═══════════════
  'ohms-law-science': dynamic(() => import('@/components/calculators/science/OhmsLawScienceCalculator')),
  'speed-of-sound': dynamic(() => import('@/components/calculators/science/SpeedOfSoundCalculator')),
  'refractive-index': dynamic(() => import('@/components/calculators/science/RefractiveIndexCalculator')),
  'doppler-effect': dynamic(() => import('@/components/calculators/science/DopplerEffectCalculator')),
  'heat-transfer': dynamic(() => import('@/components/calculators/science/HeatTransferCalculator')),
  'radioactive-decay': dynamic(() => import('@/components/calculators/science/RadioactiveDecayCalculator')),
  'snells-law': dynamic(() => import('@/components/calculators/science/SnellsLawCalculator')),
  'buoyancy': dynamic(() => import('@/components/calculators/science/BuoyancyCalculator')),
  'surface-tension': dynamic(() => import('@/components/calculators/science/SurfaceTensionCalculator')),
  'gas-diffusion': dynamic(() => import('@/components/calculators/science/GasDiffusionCalculator')),

  // ═══════════════ LANDSCAPING (10) ═══════════════
  'sod': dynamic(() => import('@/components/calculators/landscaping/SodCalculator')),
  'topsoil': dynamic(() => import('@/components/calculators/landscaping/TopsoilCalculator')),
  'landscape-rock': dynamic(() => import('@/components/calculators/landscaping/LandscapeRockCalculator')),
  'mulch-bed': dynamic(() => import('@/components/calculators/landscaping/MulchBedCalculator')),
  'paver': dynamic(() => import('@/components/calculators/landscaping/PaverCalculator')),
  'lawn-area': dynamic(() => import('@/components/calculators/landscaping/LawnAreaCalculator')),
  'plant-spacing': dynamic(() => import('@/components/calculators/landscaping/PlantSpacingCalculator')),
  'edging': dynamic(() => import('@/components/calculators/landscaping/EdgingCalculator')),
  'water-feature': dynamic(() => import('@/components/calculators/landscaping/WaterFeatureCalculator')),
  'retaining-wall': dynamic(() => import('@/components/calculators/landscaping/RetainingWallCalculator')),

  // ═══════════════ PLUMBING (10) ═══════════════
  'pipe-volume': dynamic(() => import('@/components/calculators/plumbing/PipeVolumeCalculator')),
  'flow-rate': dynamic(() => import('@/components/calculators/plumbing/FlowRateCalculator')),
  'pipe-sizing': dynamic(() => import('@/components/calculators/plumbing/PipeSizingCalculator')),
  'water-pressure-plumbing': dynamic(() => import('@/components/calculators/plumbing/WaterPressureCalculator')),
  'drainage': dynamic(() => import('@/components/calculators/plumbing/DrainageCalculator')),
  'tank-size': dynamic(() => import('@/components/calculators/plumbing/TankSizeCalculator')),
  'gpm-calculator': dynamic(() => import('@/components/calculators/plumbing/GPMCalculator')),
  'pipe-length': dynamic(() => import('@/components/calculators/plumbing/PipeLengthCalculator')),
  'water-heater-size': dynamic(() => import('@/components/calculators/plumbing/WaterHeaterSizeCalculator')),
  'septic-tank': dynamic(() => import('@/components/calculators/plumbing/SepticTankCalculator')),

  // ═══════════════ ELECTRICAL (10) ═══════════════
  'wire-size': dynamic(() => import('@/components/calculators/electrical/WireSizeCalculator')),
  'circuit-load': dynamic(() => import('@/components/calculators/electrical/CircuitLoadCalculator')),
  'amp-calc': dynamic(() => import('@/components/calculators/electrical/AmpCalculator')),
  'kilowatt-hour': dynamic(() => import('@/components/calculators/electrical/KilowattHourCalculator')),
  'transformer': dynamic(() => import('@/components/calculators/electrical/TransformerCalculator')),
  'power-factor': dynamic(() => import('@/components/calculators/electrical/PowerFactorCalculator')),
  'generator-size': dynamic(() => import('@/components/calculators/electrical/GeneratorSizeCalculator')),
  'fuse-size': dynamic(() => import('@/components/calculators/electrical/FuseSizeCalculator')),
  'solar-inverter': dynamic(() => import('@/components/calculators/electrical/SolarInverterCalculator')),
  'battery-capacity': dynamic(() => import('@/components/calculators/electrical/BatteryCapacityCalculator')),

  // ═══════════════ MATH EXPANSION (15) ═══════════════
  'derivative': dynamic(() => import('@/components/calculators/math/DerivativeCalculator')),
  'integral': dynamic(() => import('@/components/calculators/math/IntegralCalculator')),
  'limit': dynamic(() => import('@/components/calculators/math/LimitCalculator')),
  'system-equations': dynamic(() => import('@/components/calculators/math/SystemEquationsCalculator')),
  'complex-numbers': dynamic(() => import('@/components/calculators/math/ComplexNumberCalculator')),
  'matrix-determinant': dynamic(() => import('@/components/calculators/math/MatrixDeterminantCalculator')),
  'polynomial-roots': dynamic(() => import('@/components/calculators/math/PolynomialRootsCalculator')),
  'arithmetic-sequence': dynamic(() => import('@/components/calculators/math/ArithmeticSequenceCalculator')),
  'geometric-sequence': dynamic(() => import('@/components/calculators/math/GeometricSequenceCalculator')),
  'combination-repetition': dynamic(() => import('@/components/calculators/math/CombinationWithRepetitionCalculator')),
  'factorial': dynamic(() => import('@/components/calculators/math/FactorialCalculator')),
  'modulo': dynamic(() => import('@/components/calculators/math/ModuloCalculator')),
  'absolute-value': dynamic(() => import('@/components/calculators/math/AbsoluteValueCalculator')),
  'cube-root': dynamic(() => import('@/components/calculators/math/CubeRootCalculator')),
  'nth-root': dynamic(() => import('@/components/calculators/math/NthRootCalculator')),

  // ═══════════════ FINANCE EXPANSION (15) ═══════════════
  'bond-price': dynamic(() => import('@/components/calculators/finance/BondPriceCalculator')),
  'dividend-yield': dynamic(() => import('@/components/calculators/finance/DividendYieldCalculator')),
  'pe-ratio': dynamic(() => import('@/components/calculators/finance/PEratioCalculator')),
  'ebitda-finance': dynamic(() => import('@/components/calculators/finance/EBITDACalculatorFinance')),
  'amortization-schedule': dynamic(() => import('@/components/calculators/finance/AmortizationScheduleCalculator')),
  'net-worth': dynamic(() => import('@/components/calculators/finance/NetWorthCalculator')),
  'loan-payoff-early': dynamic(() => import('@/components/calculators/finance/LoanPayoffEarlyCalculator')),
  'cagr': dynamic(() => import('@/components/calculators/finance/CompoundAnnualGrowthCalculator')),
  'dividend-reinvestment': dynamic(() => import('@/components/calculators/finance/DividendReinvestmentCalculator')),
  'credit-utilization': dynamic(() => import('@/components/calculators/finance/CreditUtilizationCalculator')),
  'mortgage-affordability': dynamic(() => import('@/components/calculators/finance/MortgageAffordabilityCalculator')),
  'heloc': dynamic(() => import('@/components/calculators/finance/HELOCCalculator')),
  'fire': dynamic(() => import('@/components/calculators/finance/FIRECalculator')),
  'cost-of-living': dynamic(() => import('@/components/calculators/finance/CostOfLivingCalculator')),
  'price-elasticity': dynamic(() => import('@/components/calculators/finance/PriceElasticityCalculator')),

  // ═══════════════ HEALTH EXPANSION (15) ═══════════════
  'waist-hip-ratio': dynamic(() => import('@/components/calculators/health/WaistToHipCalculator')),
  'waist-height-ratio': dynamic(() => import('@/components/calculators/health/WaistToHeightCalculator')),
  'ibuprofen-dose': dynamic(() => import('@/components/calculators/health/IbuprofenDoseCalculator')),
  'acetaminophen-dose': dynamic(() => import('@/components/calculators/health/AcetaminophenDoseCalculator')),
  'creatinine-clearance': dynamic(() => import('@/components/calculators/health/CreatinineClearanceCalculator')),
  'anion-gap': dynamic(() => import('@/components/calculators/health/AnionGapCalculator')),
  'map-calculator': dynamic(() => import('@/components/calculators/health/MAPCalculator')),
  'pulse-pressure': dynamic(() => import('@/components/calculators/health/PulsePressureCalculator')),
  'adjusted-body-weight': dynamic(() => import('@/components/calculators/health/AdjustedBodyWeightCalculator')),
  'rmr': dynamic(() => import('@/components/calculators/health/RMRCalculator')),
  'fat-intake': dynamic(() => import('@/components/calculators/health/FatIntakeCalculator')),
  'fiber-intake': dynamic(() => import('@/components/calculators/health/FiberIntakeCalculator')),
  'bp-category': dynamic(() => import('@/components/calculators/health/BloodPressureCategoryCalculator')),
  'child-bmi': dynamic(() => import('@/components/calculators/health/ChildBMICalculator')),
  'ideal-resting-hr': dynamic(() => import('@/components/calculators/health/IdealHeartRateCalculator')),

  // ═══════════════ CONVERSION EXPANSION (15) ═══════════════
  'volume-converter': dynamic(() => import('@/components/calculators/conversion/VolumeConverter')),
  'area-converter': dynamic(() => import('@/components/calculators/conversion/AreaConverter')),
  'time-converter': dynamic(() => import('@/components/calculators/conversion/TimeConverter')),
  'density-converter': dynamic(() => import('@/components/calculators/conversion/DensityConverter')),
  'force-converter': dynamic(() => import('@/components/calculators/conversion/ForceConverter')),
  'frequency-converter': dynamic(() => import('@/components/calculators/conversion/FrequencyConverter')),
  'illuminance-converter': dynamic(() => import('@/components/calculators/conversion/IlluminanceConverter')),
  'magnetic-flux-converter': dynamic(() => import('@/components/calculators/conversion/MagneticFluxConverter')),
  'radiation-converter': dynamic(() => import('@/components/calculators/conversion/RadiationConverter')),
  'viscosity-converter': dynamic(() => import('@/components/calculators/conversion/ViscosityConverter')),
  'acceleration-converter': dynamic(() => import('@/components/calculators/conversion/AccelerationConverter')),
  'flow-rate-converter': dynamic(() => import('@/components/calculators/conversion/FlowRateConverter')),
  'torque-converter': dynamic(() => import('@/components/calculators/conversion/TorqueConverterConverter')),
  'specific-energy-converter': dynamic(() => import('@/components/calculators/conversion/SpecificEnergyConverter')),
  'heat-capacity-converter': dynamic(() => import('@/components/calculators/conversion/HeatCapacityConverter')),

  // ═══════════════ CONSTRUCTION EXPANSION (15) ═══════════════
  'brick': dynamic(() => import('@/components/calculators/construction/BrickCalculator')),
  'insulation': dynamic(() => import('@/components/calculators/construction/InsulationCalculator')),
  'fence': dynamic(() => import('@/components/calculators/construction/FenceCalculator')),
  'deck': dynamic(() => import('@/components/calculators/construction/DeckCalculator')),
  'asphalt': dynamic(() => import('@/components/calculators/construction/AsphaltCalculator')),
  'siding': dynamic(() => import('@/components/calculators/construction/SidingCalculator')),
  'concrete-block': dynamic(() => import('@/components/calculators/construction/ConcreteBlockCalculator')),
  'rebar': dynamic(() => import('@/components/calculators/construction/RebarCalculator')),
  'excavation': dynamic(() => import('@/components/calculators/construction/ExcavationCalculator')),
  'roof-pitch': dynamic(() => import('@/components/calculators/construction/RoofPitchCalculator')),
  'gutter': dynamic(() => import('@/components/calculators/construction/GutterCalculator')),
  'window-area': dynamic(() => import('@/components/calculators/construction/WindowAreaCalculator')),
  'door-size': dynamic(() => import('@/components/calculators/construction/DoorSizeCalculator')),
  'cement-mortar': dynamic(() => import('@/components/calculators/construction/CementMortarCalculator')),
  'screed': dynamic(() => import('@/components/calculators/construction/ScreedCalculator')),

  // ═══════════════ EVERYDAY EXPANSION (15) ═══════════════
  'tip-plus': dynamic(() => import('@/components/calculators/everyday/TipCalculatorPlus')),
  'age-difference': dynamic(() => import('@/components/calculators/everyday/AgeDifferenceCalculator')),
  'dog-age': dynamic(() => import('@/components/calculators/everyday/DogAgeCalculator')),
  'cat-age': dynamic(() => import('@/components/calculators/everyday/CatAgeCalculator')),
  'fuel-cost-everyday': dynamic(() => import('@/components/calculators/everyday/FuelCostCalculatorEveryday')),
  'electricity-bill': dynamic(() => import('@/components/calculators/everyday/ElectricityBillCalculator')),
  'grocery-budget': dynamic(() => import('@/components/calculators/everyday/GroceryBudgetCalculator')),
  'party-planning': dynamic(() => import('@/components/calculators/everyday/PartyPlanningCalculator')),
  'sleep-debt': dynamic(() => import('@/components/calculators/everyday/SleepDebtCalculator')),
  'screen-time': dynamic(() => import('@/components/calculators/everyday/ScreenTimeCalculator')),
  'commute-cost': dynamic(() => import('@/components/calculators/everyday/CommuteCostCalculator')),
  'pet-food': dynamic(() => import('@/components/calculators/everyday/PetFoodCalculator')),
  'laundry-cost': dynamic(() => import('@/components/calculators/everyday/LaundryCostCalculator')),
  'subscription': dynamic(() => import('@/components/calculators/everyday/SubscriptionCalculator')),
  'retirement-countdown': dynamic(() => import('@/components/calculators/everyday/RetirementCountdownCalculator')),
}

export function getCalculatorComponent(slug: string): React.ComponentType | null {
  return calculatorComponents[slug] || null
}
