// Master Calculator Registry
// Every calculator in the platform is registered here

export type CalculatorCategory =
  | 'math'
  | 'finance'
  | 'health'
  | 'date-time'
  | 'conversion'
  | 'everyday'
  | 'islamic'
  | 'construction'
  | 'engineering'
  | 'geometry'
  | 'statistics'
  | 'trigonometry'
  | 'misc'

export type CalculatorMode = 'retro' | 'form'

export interface CalculatorEntry {
  slug: string
  name: string
  shortName: string
  category: CalculatorCategory
  description: string
  keywords: string[]
  mode: CalculatorMode // primary UI mode
  icon: string // lucide icon name
  apiPowered?: boolean // true if calculator uses external API
}

export const CATEGORY_LABELS: Record<CalculatorCategory, string> = {
  math: 'Math',
  finance: 'Finance',
  health: 'Health & Fitness',
  'date-time': 'Date & Time',
  conversion: 'Conversion',
  everyday: 'Everyday Tools',
  islamic: 'Islamic',
  construction: 'Construction',
  engineering: 'Engineering',
  geometry: 'Geometry',
  statistics: 'Statistics',
  trigonometry: 'Trigonometry',
  misc: 'Other',
}

export const CATEGORY_COLORS: Record<CalculatorCategory, { bg: string; text: string; border: string }> = {
  math: { bg: 'bg-blue-50', text: 'text-blue-600', border: 'border-blue-200' },
  finance: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
  health: { bg: 'bg-rose-50', text: 'text-rose-600', border: 'border-rose-200' },
  'date-time': { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
  conversion: { bg: 'bg-emerald-50', text: 'text-emerald-600', border: 'border-emerald-200' },
  everyday: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200' },
  islamic: { bg: 'bg-teal-50', text: 'text-teal-600', border: 'border-teal-200' },
  construction: { bg: 'bg-orange-50', text: 'text-orange-600', border: 'border-orange-200' },
  engineering: { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200' },
  geometry: { bg: 'bg-lime-50', text: 'text-lime-700', border: 'border-lime-200' },
  statistics: { bg: 'bg-sky-50', text: 'text-sky-700', border: 'border-sky-200' },
  trigonometry: { bg: 'bg-fuchsia-50', text: 'text-fuchsia-700', border: 'border-fuchsia-200' },
  misc: { bg: 'bg-slate-50', text: 'text-slate-600', border: 'border-slate-200' },
}

export const calculators: CalculatorEntry[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ MATH (25 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'basic',
    name: 'Basic Calculator',
    shortName: 'Basic',
    category: 'math',
    description: 'Simple everyday arithmetic: add, subtract, multiply, divide with a retro LCD display.',
    keywords: ['basic calculator', 'simple calculator', 'arithmetic', 'add subtract multiply divide'],
    mode: 'retro',
    icon: 'Calculator',
  },
  {
    slug: 'scientific',
    name: 'Scientific Calculator',
    shortName: 'Scientific',
    category: 'math',
    description: 'Advanced scientific calculator with trigonometry, logarithms, powers, and constants.',
    keywords: ['scientific calculator', 'sin cos tan', 'logarithm', 'trigonometry'],
    mode: 'retro',
    icon: 'FlaskConical',
  },
  {
    slug: 'percentage',
    name: 'Percentage Calculator',
    shortName: 'Percentage',
    category: 'math',
    description: 'Calculate percentages: what is X% of Y, percentage change, and more.',
    keywords: ['percentage calculator', 'percent', 'percentage change', 'percentage increase decrease'],
    mode: 'form',
    icon: 'Percent',
  },
  {
    slug: 'fraction',
    name: 'Fraction Calculator',
    shortName: 'Fractions',
    category: 'math',
    description: 'Add, subtract, multiply, divide fractions. Simplify and convert to decimals.',
    keywords: ['fraction calculator', 'add fractions', 'simplify fraction'],
    mode: 'form',
    icon: 'Divide',
  },
  {
    slug: 'area',
    name: 'Area Calculator',
    shortName: 'Area',
    category: 'math',
    description: 'Calculate area of rectangles, circles, triangles, trapezoids, and ellipses.',
    keywords: ['area calculator', 'rectangle area', 'circle area', 'triangle area'],
    mode: 'form',
    icon: 'Square',
  },
  {
    slug: 'volume',
    name: 'Volume Calculator',
    shortName: 'Volume',
    category: 'math',
    description: 'Calculate volume of cubes, spheres, cylinders, cones, and pyramids.',
    keywords: ['volume calculator', 'cube volume', 'sphere volume', 'cylinder volume'],
    mode: 'form',
    icon: 'Box',
  },
  {
    slug: 'quadratic',
    name: 'Quadratic Equation Solver',
    shortName: 'Quadratic',
    category: 'math',
    description: 'Solve ax² + bx + c = 0. Find roots, discriminant, and vertex.',
    keywords: ['quadratic equation', 'solve quadratic', 'roots', 'discriminant'],
    mode: 'form',
    icon: 'TrendingUp',
  },
  {
    slug: 'statistics',
    name: 'Statistics Calculator',
    shortName: 'Statistics',
    category: 'math',
    description: 'Calculate mean, median, mode, standard deviation, and variance from a data set.',
    keywords: ['statistics calculator', 'mean', 'median', 'mode', 'standard deviation'],
    mode: 'form',
    icon: 'BarChart3',
  },
  {
    slug: 'gcd-lcm',
    name: 'GCD & LCM Calculator',
    shortName: 'GCD/LCM',
    category: 'math',
    description: 'Find the Greatest Common Divisor and Least Common Multiple of two or more numbers.',
    keywords: ['gcd calculator', 'lcm calculator', 'greatest common divisor', 'least common multiple'],
    mode: 'form',
    icon: 'GitMerge',
  },
  {
    slug: 'number-base',
    name: 'Number Base Converter',
    shortName: 'Base Convert',
    category: 'math',
    description: 'Convert between binary, octal, decimal, and hexadecimal number systems.',
    keywords: ['binary converter', 'hex converter', 'octal', 'number base'],
    mode: 'form',
    icon: 'Binary',
  },
  {
    slug: 'exponent',
    name: 'Exponent Calculator',
    shortName: 'Exponent',
    category: 'math',
    description: 'Calculate powers, roots, and exponential expressions.',
    keywords: ['exponent calculator', 'power calculator', 'roots'],
    mode: 'form',
    icon: 'Superscript',
  },
  {
    slug: 'permutation-combination',
    name: 'Permutation & Combination',
    shortName: 'nPr / nCr',
    category: 'math',
    description: 'Calculate permutations (nPr) and combinations (nCr) with factorial support.',
    keywords: ['permutation', 'combination', 'nPr', 'nCr', 'factorial'],
    mode: 'form',
    icon: 'Shuffle',
  },
  {
    slug: 'ratio',
    name: 'Ratio Calculator',
    shortName: 'Ratio',
    category: 'math',
    description: 'Simplify ratios, find equivalent ratios, and solve proportions.',
    keywords: ['ratio calculator', 'proportion', 'simplify ratio'],
    mode: 'form',
    icon: 'Scale',
  },
  {
    slug: 'logarithm',
    name: 'Logarithm Calculator',
    shortName: 'Logarithm',
    category: 'math',
    description: 'Calculate natural log (ln), common log (log₁₀), and log with custom base.',
    keywords: ['logarithm calculator', 'log', 'natural log', 'ln'],
    mode: 'form',
    icon: 'Activity',
  },
  {
    slug: 'pythagorean',
    name: 'Pythagorean Theorem Calculator',
    shortName: 'Pythagorean',
    category: 'math',
    description: 'Find the missing side of a right triangle using a² + b² = c².',
    keywords: ['pythagorean theorem', 'right triangle', 'hypotenuse', 'triangle sides'],
    mode: 'form',
    icon: 'Triangle',
  },
  {
    slug: 'circle',
    name: 'Circle Calculator',
    shortName: 'Circle',
    category: 'math',
    description: 'Calculate circle area, circumference, diameter, and radius from any known value.',
    keywords: ['circle calculator', 'circumference', 'diameter', 'radius', 'pi'],
    mode: 'form',
    icon: 'Circle',
  },
  {
    slug: 'triangle',
    name: 'Triangle Calculator',
    shortName: 'Triangle',
    category: 'math',
    description: 'Calculate area, angles, and sides of any triangle using various formulas.',
    keywords: ['triangle calculator', 'triangle area', 'sine cosine', 'heron formula'],
    mode: 'form',
    icon: 'TriangleRight',
  },
  {
    slug: 'prime-factorization',
    name: 'Prime Factorization Calculator',
    shortName: 'Prime Factors',
    category: 'math',
    description: 'Find prime factors of any number and check if a number is prime.',
    keywords: ['prime factorization', 'prime numbers', 'factors', 'is prime'],
    mode: 'form',
    icon: 'Hash',
  },
  {
    slug: 'rounding',
    name: 'Rounding Calculator',
    shortName: 'Rounding',
    category: 'math',
    description: 'Round numbers to nearest integer, decimal places, or significant figures.',
    keywords: ['rounding calculator', 'round number', 'significant figures', 'decimal places'],
    mode: 'form',
    icon: 'AlignCenterHorizontal',
  },
  {
    slug: 'scientific-notation',
    name: 'Scientific Notation Calculator',
    shortName: 'Sci Notation',
    category: 'math',
    description: 'Convert to and from scientific notation (e.g., 3.5 × 10⁴).',
    keywords: ['scientific notation', 'e notation', 'exponential notation'],
    mode: 'form',
    icon: 'Subscript',
  },
  {
    slug: 'standard-deviation',
    name: 'Standard Deviation Calculator',
    shortName: 'Std Dev',
    category: 'math',
    description: 'Calculate population and sample standard deviation with step-by-step breakdown.',
    keywords: ['standard deviation', 'variance', 'statistics', 'data analysis'],
    mode: 'form',
    icon: 'BarChart4',
  },
  {
    slug: 'mean-median-mode',
    name: 'Mean, Median, Mode Calculator',
    shortName: 'Mean/Med/Mode',
    category: 'math',
    description: 'Find the mean, median, mode, and range of any data set instantly.',
    keywords: ['mean median mode', 'average calculator', 'central tendency', 'range'],
    mode: 'form',
    icon: 'BarChartHorizontal',
  },
  {
    slug: 'z-score',
    name: 'Z-Score Calculator',
    shortName: 'Z-Score',
    category: 'math',
    description: 'Calculate z-scores and find probabilities for normal distributions.',
    keywords: ['z-score', 'standard score', 'normal distribution', 'statistics'],
    mode: 'form',
    icon: 'Sigma',
  },
  {
    slug: 'confidence-interval',
    name: 'Confidence Interval Calculator',
    shortName: 'Confidence',
    category: 'math',
    description: 'Calculate confidence intervals for means and proportions.',
    keywords: ['confidence interval', 'margin of error', 'statistics', 'sample size'],
    mode: 'form',
    icon: 'ShieldCheck',
  },
  {
    slug: 'probability',
    name: 'Probability Calculator',
    shortName: 'Probability',
    category: 'math',
    description: 'Calculate probability of events, combinations, and conditional probability.',
    keywords: ['probability calculator', 'odds', 'chance', 'likelihood'],
    mode: 'form',
    icon: 'Dices',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ FINANCE (30 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'loan-emi',
    name: 'Loan EMI Calculator',
    shortName: 'Loan EMI',
    category: 'finance',
    description: 'Calculate monthly EMI, total interest, and payment schedule for any loan.',
    keywords: ['emi calculator', 'loan calculator', 'monthly payment', 'amortization'],
    mode: 'form',
    icon: 'Landmark',
  },
  {
    slug: 'compound-interest',
    name: 'Compound Interest Calculator',
    shortName: 'Compound Interest',
    category: 'finance',
    description: 'Calculate compound interest with flexible compounding frequencies.',
    keywords: ['compound interest', 'investment growth', 'compounding'],
    mode: 'form',
    icon: 'TrendingUp',
  },
  {
    slug: 'simple-interest',
    name: 'Simple Interest Calculator',
    shortName: 'Simple Interest',
    category: 'finance',
    description: 'Calculate simple interest: I = P × R × T.',
    keywords: ['simple interest', 'interest calculator'],
    mode: 'form',
    icon: 'Coins',
  },
  {
    slug: 'sip',
    name: 'SIP Calculator',
    shortName: 'SIP',
    category: 'finance',
    description: 'Systematic Investment Plan calculator: project your wealth growth over time.',
    keywords: ['sip calculator', 'mutual fund', 'investment plan'],
    mode: 'form',
    icon: 'PiggyBank',
  },
  {
    slug: 'tip',
    name: 'Tip Calculator',
    shortName: 'Tip',
    category: 'finance',
    description: 'Calculate tip amount and split bills between multiple people.',
    keywords: ['tip calculator', 'gratuity', 'bill split'],
    mode: 'form',
    icon: 'HandCoins',
  },
  {
    slug: 'discount',
    name: 'Discount Calculator',
    shortName: 'Discount',
    category: 'finance',
    description: 'Calculate discount amount, final price, and savings.',
    keywords: ['discount calculator', 'sale price', 'savings'],
    mode: 'form',
    icon: 'Tag',
  },
  {
    slug: 'profit-margin',
    name: 'Profit Margin Calculator',
    shortName: 'Profit Margin',
    category: 'finance',
    description: 'Calculate gross profit margin, net margin, and markup percentage.',
    keywords: ['profit margin', 'markup', 'gross margin'],
    mode: 'form',
    icon: 'Receipt',
  },
  {
    slug: 'roi',
    name: 'ROI Calculator',
    shortName: 'ROI',
    category: 'finance',
    description: 'Calculate Return on Investment with gain/loss analysis.',
    keywords: ['roi calculator', 'return on investment'],
    mode: 'form',
    icon: 'LineChart',
  },
  {
    slug: 'salary',
    name: 'Salary Calculator',
    shortName: 'Salary',
    category: 'finance',
    description: 'Convert between hourly, daily, weekly, monthly, and annual salary.',
    keywords: ['salary calculator', 'hourly to annual', 'wage converter'],
    mode: 'form',
    icon: 'Wallet',
  },
  {
    slug: 'mortgage',
    name: 'Mortgage Calculator',
    shortName: 'Mortgage',
    category: 'finance',
    description: 'Calculate monthly mortgage payments, total interest, and amortization.',
    keywords: ['mortgage calculator', 'home loan', 'house payment'],
    mode: 'form',
    icon: 'Home',
  },
  {
    slug: 'inflation',
    name: 'Inflation Calculator',
    shortName: 'Inflation',
    category: 'finance',
    description: 'Calculate the effect of inflation on purchasing power over time.',
    keywords: ['inflation calculator', 'purchasing power', 'cost of living'],
    mode: 'form',
    icon: 'TrendingDown',
  },
  {
    slug: 'break-even',
    name: 'Break-Even Calculator',
    shortName: 'Break-Even',
    category: 'finance',
    description: 'Find the break-even point: units and revenue needed to cover costs.',
    keywords: ['break even', 'breakeven analysis', 'cost analysis'],
    mode: 'form',
    icon: 'Target',
  },
  {
    slug: 'savings-goal',
    name: 'Savings Goal Calculator',
    shortName: 'Savings Goal',
    category: 'finance',
    description: 'How much to save monthly to reach your financial goal.',
    keywords: ['savings goal', 'savings calculator', 'financial planning'],
    mode: 'form',
    icon: 'Goal',
  },
  {
    slug: 'currency',
    name: 'Currency Converter',
    shortName: 'Currency',
    category: 'finance',
    description: 'Convert between major world currencies with real-time exchange rates.',
    keywords: ['currency converter', 'exchange rate', 'forex', 'real time rates'],
    mode: 'form',
    icon: 'ArrowLeftRight',
    apiPowered: true,
  },
  {
    slug: 'auto-loan',
    name: 'Auto Loan Calculator',
    shortName: 'Auto Loan',
    category: 'finance',
    description: 'Calculate monthly auto loan payments, total interest, and affordability.',
    keywords: ['auto loan calculator', 'car loan', 'vehicle finance', 'car payment'],
    mode: 'form',
    icon: 'Car',
  },
  {
    slug: 'credit-card-payoff',
    name: 'Credit Card Payoff Calculator',
    shortName: 'CC Payoff',
    category: 'finance',
    description: 'Find out how long it will take to pay off your credit card debt.',
    keywords: ['credit card payoff', 'debt calculator', 'credit card debt', 'payoff time'],
    mode: 'form',
    icon: 'CreditCard',
  },
  {
    slug: 'debt-to-income',
    name: 'Debt-to-Income Ratio Calculator',
    shortName: 'DTI Ratio',
    category: 'finance',
    description: 'Calculate your debt-to-income ratio to assess loan eligibility.',
    keywords: ['debt to income', 'dti ratio', 'loan eligibility', 'debt ratio'],
    mode: 'form',
    icon: 'Scale',
  },
  {
    slug: 'refinance',
    name: 'Refinance Calculator',
    shortName: 'Refinance',
    category: 'finance',
    description: 'Compare your current mortgage with a refinanced loan to see potential savings.',
    keywords: ['refinance calculator', 'mortgage refinance', 'loan refinance', 'savings'],
    mode: 'form',
    icon: 'RefreshCw',
  },
  {
    slug: 'rent-vs-buy',
    name: 'Rent vs. Buy Calculator',
    shortName: 'Rent vs Buy',
    category: 'finance',
    description: 'Compare the costs of renting versus buying a home over time.',
    keywords: ['rent vs buy', 'renting vs buying', 'home affordability', 'mortgage vs rent'],
    mode: 'form',
    icon: 'HomeIcon',
  },
  {
    slug: 'present-value',
    name: 'Present Value Calculator',
    shortName: 'Present Value',
    category: 'finance',
    description: 'Calculate the present value of future cash flows and investments.',
    keywords: ['present value', 'pv calculator', 'time value of money', 'discounting'],
    mode: 'form',
    icon: 'Clock',
  },
  {
    slug: 'future-value',
    name: 'Future Value Calculator',
    shortName: 'Future Value',
    category: 'finance',
    description: 'Calculate the future value of investments and savings with compound interest.',
    keywords: ['future value', 'fv calculator', 'investment growth', 'compound growth'],
    mode: 'form',
    icon: 'TrendingUp',
  },
  {
    slug: 'annuity',
    name: 'Annuity Calculator',
    shortName: 'Annuity',
    category: 'finance',
    description: 'Calculate annuity payments, present value, and future value of annuities.',
    keywords: ['annuity calculator', 'retirement annuity', 'pension', 'periodic payments'],
    mode: 'form',
    icon: 'CalendarClock',
  },
  {
    slug: 'retirement',
    name: 'Retirement Calculator',
    shortName: 'Retirement',
    category: 'finance',
    description: 'Estimate how much you need to save for a comfortable retirement.',
    keywords: ['retirement calculator', 'retirement savings', 'pension planning', '401k'],
    mode: 'form',
    icon: 'Umbrella',
  },
  {
    slug: '401k',
    name: '401(k) Calculator',
    shortName: '401(k)',
    category: 'finance',
    description: 'Project your 401(k) balance at retirement with employer matching.',
    keywords: ['401k calculator', 'retirement account', 'employer match', 'retirement fund'],
    mode: 'form',
    icon: 'Briefcase',
  },
  {
    slug: 'sales-tax',
    name: 'Sales Tax Calculator',
    shortName: 'Sales Tax',
    category: 'finance',
    description: 'Calculate sales tax and total price for any purchase amount.',
    keywords: ['sales tax calculator', 'vat calculator', 'tax rate', 'purchase tax'],
    mode: 'form',
    icon: 'ReceiptText',
  },
  {
    slug: 'commission',
    name: 'Commission Calculator',
    shortName: 'Commission',
    category: 'finance',
    description: 'Calculate sales commission based on rate and tiered structures.',
    keywords: ['commission calculator', 'sales commission', 'tiered commission', 'bonus'],
    mode: 'form',
    icon: 'Award',
  },
  {
    slug: 'apr',
    name: 'APR Calculator',
    shortName: 'APR',
    category: 'finance',
    description: 'Calculate the Annual Percentage Rate for loans and credit products.',
    keywords: ['apr calculator', 'annual percentage rate', 'loan cost', 'true cost'],
    mode: 'form',
    icon: 'Percent',
  },
  {
    slug: 'depreciation',
    name: 'Depreciation Calculator',
    shortName: 'Depreciation',
    category: 'finance',
    description: 'Calculate straight-line and declining balance depreciation schedules.',
    keywords: ['depreciation calculator', 'asset value', 'straight line', 'declining balance'],
    mode: 'form',
    icon: 'ChartLine',
  },
  {
    slug: 'gold-price',
    name: 'Gold Price Calculator',
    shortName: 'Gold Price',
    category: 'finance',
    description: 'Check real-time gold prices and calculate value of gold by weight and purity.',
    keywords: ['gold price', 'gold calculator', 'gold rate', 'precious metals'],
    mode: 'form',
    icon: 'Gem',
    apiPowered: true,
  },
  {
    slug: 'crypto-converter',
    name: 'Crypto Converter',
    shortName: 'Crypto',
    category: 'finance',
    description: 'Convert between cryptocurrencies and fiat with real-time market rates.',
    keywords: ['crypto converter', 'bitcoin calculator', 'ethereum', 'crypto price'],
    mode: 'form',
    icon: 'Bitcoin',
    apiPowered: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ HEALTH & FITNESS (22 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'bmi',
    name: 'BMI Calculator',
    shortName: 'BMI',
    category: 'health',
    description: 'Calculate Body Mass Index with health category classification.',
    keywords: ['bmi calculator', 'body mass index', 'weight health'],
    mode: 'form',
    icon: 'Heart',
  },
  {
    slug: 'calorie',
    name: 'Calorie & TDEE Calculator',
    shortName: 'Calories',
    category: 'health',
    description: 'Calculate your Basal Metabolic Rate and Total Daily Energy Expenditure.',
    keywords: ['calorie calculator', 'bmr', 'tdee', 'metabolism'],
    mode: 'form',
    icon: 'Flame',
  },
  {
    slug: 'body-fat',
    name: 'Body Fat Calculator',
    shortName: 'Body Fat',
    category: 'health',
    description: 'Estimate body fat percentage using the US Navy method.',
    keywords: ['body fat calculator', 'body composition', 'navy method'],
    mode: 'form',
    icon: 'User',
  },
  {
    slug: 'ideal-weight',
    name: 'Ideal Weight Calculator',
    shortName: 'Ideal Weight',
    category: 'health',
    description: 'Find your ideal weight range using multiple scientific formulas.',
    keywords: ['ideal weight', 'healthy weight', 'target weight'],
    mode: 'form',
    icon: 'Scale',
  },
  {
    slug: 'water-intake',
    name: 'Water Intake Calculator',
    shortName: 'Water Intake',
    category: 'health',
    description: 'Calculate daily water intake based on weight, activity, and climate.',
    keywords: ['water intake', 'hydration calculator', 'daily water'],
    mode: 'form',
    icon: 'Droplets',
  },
  {
    slug: 'heart-rate',
    name: 'Heart Rate Zone Calculator',
    shortName: 'Heart Rate',
    category: 'health',
    description: 'Calculate your target heart rate zones for optimal training.',
    keywords: ['heart rate zone', 'target heart rate', 'exercise zone'],
    mode: 'form',
    icon: 'HeartPulse',
  },
  {
    slug: 'macro',
    name: 'Macronutrient Calculator',
    shortName: 'Macros',
    category: 'health',
    description: 'Calculate daily protein, carbs, and fat intake based on your goals.',
    keywords: ['macro calculator', 'macronutrient', 'protein carbs fat'],
    mode: 'form',
    icon: 'Apple',
  },
  {
    slug: 'pregnancy',
    name: 'Pregnancy Due Date Calculator',
    shortName: 'Due Date',
    category: 'health',
    description: 'Estimate pregnancy due date and track trimester milestones.',
    keywords: ['pregnancy calculator', 'due date', 'trimester'],
    mode: 'form',
    icon: 'Baby',
  },
  {
    slug: 'bmr',
    name: 'BMR Calculator',
    shortName: 'BMR',
    category: 'health',
    description: 'Calculate your Basal Metabolic Rate using Mifflin-St Jeor equation.',
    keywords: ['bmr calculator', 'basal metabolic rate', 'calories burned at rest'],
    mode: 'form',
    icon: 'Activity',
  },
  {
    slug: 'tdee',
    name: 'TDEE Calculator',
    shortName: 'TDEE',
    category: 'health',
    description: 'Calculate Total Daily Energy Expenditure based on activity level.',
    keywords: ['tdee calculator', 'total daily energy expenditure', 'maintenance calories'],
    mode: 'form',
    icon: 'Zap',
  },
  {
    slug: 'one-rep-max',
    name: 'One Rep Max Calculator',
    shortName: '1RM',
    category: 'health',
    description: 'Estimate your one-rep max using various lifting formulas.',
    keywords: ['one rep max', '1rm calculator', 'strength calculator', 'lifting'],
    mode: 'form',
    icon: 'Dumbbell',
  },
  {
    slug: 'ovulation',
    name: 'Ovulation Calculator',
    shortName: 'Ovulation',
    category: 'health',
    description: 'Predict your fertile window and ovulation date based on cycle length.',
    keywords: ['ovulation calculator', 'fertility', 'fertile window', 'conception'],
    mode: 'form',
    icon: 'Flower2',
  },
  {
    slug: 'bac',
    name: 'BAC Calculator',
    shortName: 'BAC',
    category: 'health',
    description: 'Estimate Blood Alcohol Content based on drinks, weight, and time.',
    keywords: ['bac calculator', 'blood alcohol', 'drunk calculator', 'alcohol level'],
    mode: 'form',
    icon: 'Wine',
  },
  {
    slug: 'pace',
    name: 'Running Pace Calculator',
    shortName: 'Pace',
    category: 'health',
    description: 'Calculate running pace, split times, and race finish predictions.',
    keywords: ['pace calculator', 'running pace', 'split time', 'race predictor'],
    mode: 'form',
    icon: 'Footprints',
  },
  {
    slug: 'protein',
    name: 'Protein Calculator',
    shortName: 'Protein',
    category: 'health',
    description: 'Calculate daily protein needs based on weight, activity, and goals.',
    keywords: ['protein calculator', 'daily protein', 'muscle building', 'protein intake'],
    mode: 'form',
    icon: 'Beef',
  },
  {
    slug: 'carbohydrate',
    name: 'Carbohydrate Calculator',
    shortName: 'Carbs',
    category: 'health',
    description: 'Calculate daily carbohydrate needs based on diet type and activity.',
    keywords: ['carb calculator', 'carbohydrate intake', 'keto', 'low carb'],
    mode: 'form',
    icon: 'Wheat',
  },
  {
    slug: 'lean-body-mass',
    name: 'Lean Body Mass Calculator',
    shortName: 'LBM',
    category: 'health',
    description: 'Estimate your lean body mass and body fat percentage.',
    keywords: ['lean body mass', 'lbm calculator', 'muscle mass', 'body composition'],
    mode: 'form',
    icon: 'PersonStanding',
  },
  {
    slug: 'body-surface-area',
    name: 'Body Surface Area Calculator',
    shortName: 'BSA',
    category: 'health',
    description: 'Calculate body surface area using Du Bois and Mosteller formulas.',
    keywords: ['body surface area', 'bsa calculator', 'medical dosing', 'du bois'],
    mode: 'form',
    icon: 'Scan',
  },
  {
    slug: 'gfr',
    name: 'GFR Calculator',
    shortName: 'GFR',
    category: 'health',
    description: 'Estimate Glomerular Filtration Rate for kidney function assessment.',
    keywords: ['gfr calculator', 'kidney function', 'creatinine', 'renal'],
    mode: 'form',
    icon: 'Kidney',
  },
  {
    slug: 'pregnancy-weight-gain',
    name: 'Pregnancy Weight Gain Calculator',
    shortName: 'Preg Weight',
    category: 'health',
    description: 'Track healthy weight gain during pregnancy by trimester.',
    keywords: ['pregnancy weight gain', 'trimester weight', 'healthy pregnancy weight'],
    mode: 'form',
    icon: 'Weight',
  },
  {
    slug: 'conception',
    name: 'Conception Calculator',
    shortName: 'Conception',
    category: 'health',
    description: 'Estimate conception date and fertile window based on due date or LMP.',
    keywords: ['conception calculator', 'conception date', 'fertile window', 'pregnancy'],
    mode: 'form',
    icon: 'CalendarHeart',
  },
  {
    slug: 'period',
    name: 'Period Calculator',
    shortName: 'Period',
    category: 'health',
    description: 'Track menstrual cycle, predict next period, and identify fertile days.',
    keywords: ['period calculator', 'menstrual cycle', 'period tracker', 'fertility'],
    mode: 'form',
    icon: 'CalendarDays',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ DATE & TIME (12 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'age',
    name: 'Age Calculator',
    shortName: 'Age',
    category: 'date-time',
    description: 'Calculate exact age in years, months, and days from your birth date.',
    keywords: ['age calculator', 'how old am i', 'date of birth'],
    mode: 'form',
    icon: 'Cake',
  },
  {
    slug: 'date-difference',
    name: 'Date Difference Calculator',
    shortName: 'Date Diff',
    category: 'date-time',
    description: 'Find the exact difference between two dates in days, weeks, months, and years.',
    keywords: ['date difference', 'days between dates', 'date calculator'],
    mode: 'form',
    icon: 'CalendarRange',
  },
  {
    slug: 'time',
    name: 'Time Calculator',
    shortName: 'Time',
    category: 'date-time',
    description: 'Add or subtract hours, minutes, and seconds.',
    keywords: ['time calculator', 'add time', 'subtract time'],
    mode: 'form',
    icon: 'Clock',
  },
  {
    slug: 'countdown',
    name: 'Countdown Calculator',
    shortName: 'Countdown',
    category: 'date-time',
    description: 'Count days until a future event: birthday, holiday, deadline.',
    keywords: ['countdown', 'days until', 'date countdown'],
    mode: 'form',
    icon: 'Timer',
  },
  {
    slug: 'day-of-week',
    name: 'Day of the Week Calculator',
    shortName: 'Day of Week',
    category: 'date-time',
    description: 'Find out what day of the week any date falls on.',
    keywords: ['day of week', 'what day was', 'zellers congruence', 'doomsday rule'],
    mode: 'form',
    icon: 'CalendarCheck',
  },
  {
    slug: 'time-zone',
    name: 'Time Zone Converter',
    shortName: 'Time Zone',
    category: 'date-time',
    description: 'Convert times between different time zones around the world.',
    keywords: ['time zone converter', 'world clock', 'time difference', 'gmt converter'],
    mode: 'form',
    icon: 'Globe',
  },
  {
    slug: 'time-duration',
    name: 'Time Duration Calculator',
    shortName: 'Duration',
    category: 'date-time',
    description: 'Calculate the duration between two times in hours, minutes, and seconds.',
    keywords: ['time duration', 'hours between', 'elapsed time', 'time difference'],
    mode: 'form',
    icon: 'Hourglass',
  },
  {
    slug: 'hours',
    name: 'Hours Calculator',
    shortName: 'Hours',
    category: 'date-time',
    description: 'Calculate total hours worked and overtime from clock-in and clock-out times.',
    keywords: ['hours calculator', 'timesheet', 'work hours', 'overtime calculator'],
    mode: 'form',
    icon: 'Briefcase',
  },
  {
    slug: 'date-calculator',
    name: 'Date Calculator',
    shortName: 'Date Calc',
    category: 'date-time',
    description: 'Add or subtract days, weeks, months, or years from any date.',
    keywords: ['date calculator', 'add days to date', 'subtract days', 'future date'],
    mode: 'form',
    icon: 'CalendarPlus',
  },
  {
    slug: 'day-counter',
    name: 'Day Counter',
    shortName: 'Day Counter',
    category: 'date-time',
    description: 'Count the number of days between two dates including or excluding weekends.',
    keywords: ['day counter', 'business days', 'working days', 'days between'],
    mode: 'form',
    icon: 'Calendar',
  },
  {
    slug: 'sleep',
    name: 'Sleep Calculator',
    shortName: 'Sleep',
    category: 'date-time',
    description: 'Calculate optimal bedtime and wake-up time based on sleep cycles.',
    keywords: ['sleep calculator', 'sleep cycles', 'bedtime calculator', 'wake up time'],
    mode: 'form',
    icon: 'Moon',
  },
  {
    slug: 'time-card',
    name: 'Time Card Calculator',
    shortName: 'Time Card',
    category: 'date-time',
    description: 'Calculate weekly time card totals, regular hours, and overtime pay.',
    keywords: ['time card', 'timesheet calculator', 'weekly hours', 'payroll hours'],
    mode: 'form',
    icon: 'ClipboardList',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ CONVERSION (12 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'length',
    name: 'Length Converter',
    shortName: 'Length',
    category: 'conversion',
    description: 'Convert between meters, feet, inches, miles, kilometers, and more.',
    keywords: ['length converter', 'meters to feet', 'distance converter'],
    mode: 'form',
    icon: 'Ruler',
  },
  {
    slug: 'weight',
    name: 'Weight Converter',
    shortName: 'Weight',
    category: 'conversion',
    description: 'Convert between kilograms, pounds, ounces, grams, and stones.',
    keywords: ['weight converter', 'kg to lbs', 'mass converter'],
    mode: 'form',
    icon: 'Weight',
  },
  {
    slug: 'temperature',
    name: 'Temperature Converter',
    shortName: 'Temperature',
    category: 'conversion',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin.',
    keywords: ['temperature converter', 'celsius fahrenheit', 'kelvin'],
    mode: 'form',
    icon: 'Thermometer',
  },
  {
    slug: 'speed',
    name: 'Speed Converter',
    shortName: 'Speed',
    category: 'conversion',
    description: 'Convert between km/h, mph, m/s, knots, and more.',
    keywords: ['speed converter', 'kmh to mph', 'velocity'],
    mode: 'form',
    icon: 'Gauge',
  },
  {
    slug: 'data-storage',
    name: 'Data Storage Converter',
    shortName: 'Data',
    category: 'conversion',
    description: 'Convert between bytes, KB, MB, GB, TB, and PB.',
    keywords: ['data converter', 'bytes to gb', 'storage converter'],
    mode: 'form',
    icon: 'HardDrive',
  },
  {
    slug: 'energy',
    name: 'Energy Converter',
    shortName: 'Energy',
    category: 'conversion',
    description: 'Convert between joules, calories, kWh, BTU, and more.',
    keywords: ['energy converter', 'joules to calories', 'kwh'],
    mode: 'form',
    icon: 'Zap',
  },
  {
    slug: 'cooking',
    name: 'Cooking Converter',
    shortName: 'Cooking',
    category: 'conversion',
    description: 'Convert between cups, tablespoons, teaspoons, ml, liters, and ounces.',
    keywords: ['cooking converter', 'cups to ml', 'tablespoon'],
    mode: 'form',
    icon: 'ChefHat',
  },
  {
    slug: 'pressure',
    name: 'Pressure Converter',
    shortName: 'Pressure',
    category: 'conversion',
    description: 'Convert between pascal, bar, psi, atm, and torr.',
    keywords: ['pressure converter', 'psi to bar', 'atmospheric pressure', 'pascal'],
    mode: 'form',
    icon: 'GaugeCircle',
  },
  {
    slug: 'angle',
    name: 'Angle Converter',
    shortName: 'Angle',
    category: 'conversion',
    description: 'Convert between degrees, radians, gradians, and turns.',
    keywords: ['angle converter', 'degrees to radians', 'gradians', 'angle units'],
    mode: 'form',
    icon: 'RotateCcw',
  },
  {
    slug: 'power',
    name: 'Power Converter',
    shortName: 'Power',
    category: 'conversion',
    description: 'Convert between watts, horsepower, kilowatts, and BTU/hr.',
    keywords: ['power converter', 'watts to horsepower', 'kw to hp', 'mechanical power'],
    mode: 'form',
    icon: 'Plug',
  },
  {
    slug: 'fuel',
    name: 'Fuel Converter',
    shortName: 'Fuel',
    category: 'conversion',
    description: 'Convert between MPG, L/100km, km/L, and other fuel economy units.',
    keywords: ['fuel converter', 'mpg to l100km', 'fuel economy', 'gas mileage'],
    mode: 'form',
    icon: 'Fuel',
  },
  {
    slug: 'roman-numeral',
    name: 'Roman Numeral Converter',
    shortName: 'Roman',
    category: 'conversion',
    description: 'Convert between Arabic numbers and Roman numerals.',
    keywords: ['roman numeral converter', 'roman numbers', 'latin numerals', 'ancient numbers'],
    mode: 'form',
    icon: 'TypeOutline',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ EVERYDAY TOOLS (12 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'gpa',
    name: 'GPA Calculator',
    shortName: 'GPA',
    category: 'everyday',
    description: 'Calculate your Grade Point Average from courses and credits.',
    keywords: ['gpa calculator', 'grade calculator', 'college gpa'],
    mode: 'form',
    icon: 'GraduationCap',
  },
  {
    slug: 'random-number',
    name: 'Random Number Generator',
    shortName: 'Random',
    category: 'everyday',
    description: 'Generate random numbers within a specified range.',
    keywords: ['random number generator', 'rng', 'random'],
    mode: 'retro',
    icon: 'Dices',
  },
  {
    slug: 'password',
    name: 'Password Generator',
    shortName: 'Password',
    category: 'everyday',
    description: 'Generate strong, secure passwords with customizable options.',
    keywords: ['password generator', 'secure password', 'random password'],
    mode: 'form',
    icon: 'KeyRound',
  },
  {
    slug: 'word-counter',
    name: 'Word & Character Counter',
    shortName: 'Word Count',
    category: 'everyday',
    description: 'Count words, characters, sentences, and paragraphs in your text.',
    keywords: ['word counter', 'character counter', 'text counter'],
    mode: 'form',
    icon: 'Type',
  },
  {
    slug: 'color',
    name: 'Color Converter',
    shortName: 'Color',
    category: 'everyday',
    description: 'Convert between HEX, RGB, and HSL color formats with live preview.',
    keywords: ['color converter', 'hex to rgb', 'color picker'],
    mode: 'form',
    icon: 'Palette',
  },
  {
    slug: 'grade',
    name: 'Grade Calculator',
    shortName: 'Grade',
    category: 'everyday',
    description: 'Calculate weighted grades and final course averages.',
    keywords: ['grade calculator', 'weighted grade', 'final grade', 'course average'],
    mode: 'form',
    icon: 'ClipboardCheck',
  },
  {
    slug: 'url-encode',
    name: 'URL Encode / Decode',
    shortName: 'URL Encode',
    category: 'everyday',
    description: 'Encode and decode URLs and query parameters safely.',
    keywords: ['url encode', 'url decode', 'percent encoding', 'query string'],
    mode: 'form',
    icon: 'Link',
  },
  {
    slug: 'base64',
    name: 'Base64 Encode / Decode',
    shortName: 'Base64',
    category: 'everyday',
    description: 'Encode text to Base64 or decode Base64 back to text.',
    keywords: ['base64 encode', 'base64 decode', 'data encoding', 'text encoding'],
    mode: 'form',
    icon: 'FileCode',
  },
  {
    slug: 'ip-subnet',
    name: 'IP Subnet Calculator',
    shortName: 'IP Subnet',
    category: 'everyday',
    description: 'Calculate subnet masks, network addresses, and host ranges from IP and CIDR.',
    keywords: ['ip subnet', 'subnet calculator', 'cidr', 'network calculator'],
    mode: 'form',
    icon: 'Network',
  },
  {
    slug: 'height',
    name: 'Height Converter',
    shortName: 'Height',
    category: 'everyday',
    description: 'Convert between feet/inches and centimeters.',
    keywords: ['height converter', 'feet to cm', 'inches to cm', 'tall converter'],
    mode: 'form',
    icon: 'MoveVertical',
  },
  {
    slug: 'shoe-size',
    name: 'Shoe Size Converter',
    shortName: 'Shoe Size',
    category: 'everyday',
    description: 'Convert shoe sizes between US, UK, EU, and CM measurements.',
    keywords: ['shoe size converter', 'us to eu shoe size', 'uk shoe size', 'foot size'],
    mode: 'form',
    icon: 'Footprints',
  },
  {
    slug: 'love',
    name: 'Love Calculator',
    shortName: 'Love',
    category: 'everyday',
    description: 'A fun compatibility calculator based on names and birth dates.',
    keywords: ['love calculator', 'compatibility', 'love match', 'relationship'],
    mode: 'form',
    icon: 'Heart',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ ISLAMIC (8 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'zakat',
    name: 'Zakat Calculator',
    shortName: 'Zakat',
    category: 'islamic',
    description: 'Calculate your annual Zakat obligation on cash, gold, silver, and investments.',
    keywords: ['zakat calculator', 'islamic charity', 'zakat gold', 'zakat money', 'nisab'],
    mode: 'form',
    icon: 'HandHeart',
  },
  {
    slug: 'prayer-times',
    name: 'Prayer Times Calculator',
    shortName: 'Prayer Times',
    category: 'islamic',
    description: 'Get accurate prayer times (Fajr, Dhuhr, Asr, Maghrib, Isha) for any location.',
    keywords: ['prayer times', 'salah times', 'namaz time', 'islamic prayer', 'adhan'],
    mode: 'form',
    icon: 'Sun',
    apiPowered: true,
  },
  {
    slug: 'hijri-date',
    name: 'Hijri Date Converter',
    shortName: 'Hijri Date',
    category: 'islamic',
    description: 'Convert between Gregorian and Hijri (Islamic) calendar dates.',
    keywords: ['hijri date converter', 'islamic calendar', 'gregorian to hijri', 'umm al qura'],
    mode: 'form',
    icon: 'CalendarFold',
  },
  {
    slug: 'inheritance',
    name: 'Islamic Inheritance Calculator',
    shortName: 'Inheritance',
    category: 'islamic',
    description: 'Calculate shares of inheritance according to Islamic law (Sharia).',
    keywords: ['islamic inheritance', 'mirath', 'sharia inheritance', 'faraid'],
    mode: 'form',
    icon: 'Users',
  },
  {
    slug: 'qibla',
    name: 'Qibla Direction Calculator',
    shortName: 'Qibla',
    category: 'islamic',
    description: 'Find the Qibla direction (Kaaba bearing) from any location on Earth.',
    keywords: ['qibla direction', 'kaaba direction', 'prayer direction', 'mecca direction'],
    mode: 'form',
    icon: 'Compass',
    apiPowered: true,
  },
  {
    slug: 'ramadan',
    name: 'Ramadan Calendar',
    shortName: 'Ramadan',
    category: 'islamic',
    description: 'View Ramadan dates, fasting times, and Iftar/Suhoor schedules.',
    keywords: ['ramadan calendar', 'fasting times', 'iftar time', 'suhoor time', 'ramadan 2026'],
    mode: 'form',
    icon: 'MoonStar',
    apiPowered: true,
  },
  {
    slug: 'tahajjud',
    name: 'Tahajjud Calculator',
    shortName: 'Tahajjud',
    category: 'islamic',
    description: 'Calculate the best time for Tahajjud (night prayer) based on local prayer times.',
    keywords: ['tahajjud time', 'night prayer', 'last third of night', 'qiyam'],
    mode: 'form',
    icon: 'Moon',
  },
  {
    slug: 'hajj-dates',
    name: 'Hajj & Umrah Dates',
    shortName: 'Hajj Dates',
    category: 'islamic',
    description: 'View upcoming Hajj and Umrah dates in both Hijri and Gregorian calendars.',
    keywords: ['hajj dates', 'umrah dates', 'islamic pilgrimage', 'dhul hijjah'],
    mode: 'form',
    icon: 'Plane',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ CONSTRUCTION (10 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'concrete',
    name: 'Concrete Calculator',
    shortName: 'Concrete',
    category: 'construction',
    description: 'Calculate concrete volume, bags needed, and cost for slabs, footings, and columns.',
    keywords: ['concrete calculator', 'cement calculator', 'concrete volume', 'bags of concrete'],
    mode: 'form',
    icon: 'BrickWall',
  },
  {
    slug: 'tile',
    name: 'Tile Calculator',
    shortName: 'Tile',
    category: 'construction',
    description: 'Calculate number of tiles needed and total cost for flooring and walls.',
    keywords: ['tile calculator', 'floor tiles', 'wall tiles', 'tile cost'],
    mode: 'form',
    icon: 'Grid3x3',
  },
  {
    slug: 'gravel',
    name: 'Gravel Calculator',
    shortName: 'Gravel',
    category: 'construction',
    description: 'Calculate gravel volume and weight needed for driveways, paths, and gardens.',
    keywords: ['gravel calculator', 'aggregate calculator', 'stone volume', 'driveway gravel'],
    mode: 'form',
    icon: 'Mountain',
  },
  {
    slug: 'mulch',
    name: 'Mulch Calculator',
    shortName: 'Mulch',
    category: 'construction',
    description: 'Calculate mulch volume and bags needed for garden beds and landscaping.',
    keywords: ['mulch calculator', 'mulch volume', 'garden mulch', 'landscaping calculator'],
    mode: 'form',
    icon: 'Leaf',
  },
  {
    slug: 'roofing',
    name: 'Roofing Calculator',
    shortName: 'Roofing',
    category: 'construction',
    description: 'Estimate roofing materials, shingles, and cost based on roof dimensions.',
    keywords: ['roofing calculator', 'shingle calculator', 'roof area', 'roofing cost'],
    mode: 'form',
    icon: 'House',
  },
  {
    slug: 'stair',
    name: 'Stair Calculator',
    shortName: 'Stair',
    category: 'construction',
    description: 'Calculate stair dimensions, rise, run, and stringer length for safe stair design.',
    keywords: ['stair calculator', 'stair dimensions', 'stair rise run', 'stair stringer'],
    mode: 'form',
    icon: 'ArrowUpDown',
  },
  {
    slug: 'paint',
    name: 'Paint Calculator',
    shortName: 'Paint',
    category: 'construction',
    description: 'Estimate paint quantity and cost for walls, ceilings, and exterior surfaces.',
    keywords: ['paint calculator', 'paint quantity', 'gallons of paint', 'painting cost'],
    mode: 'form',
    icon: 'Paintbrush',
  },
  {
    slug: 'square-footage',
    name: 'Square Footage Calculator',
    shortName: 'Sq Footage',
    category: 'construction',
    description: 'Calculate square footage of rooms, houses, and irregular shapes.',
    keywords: ['square footage', 'sq ft calculator', 'room area', 'floor area'],
    mode: 'form',
    icon: 'Maximize',
  },
  {
    slug: 'drywall',
    name: 'Drywall Calculator',
    shortName: 'Drywall',
    category: 'construction',
    description: 'Estimate drywall sheets, mud, tape, and screws needed for a project.',
    keywords: ['drywall calculator', 'sheetrock', 'gypsum board', 'drywall cost'],
    mode: 'form',
    icon: 'PanelTop',
  },
  {
    slug: 'flooring',
    name: 'Flooring Calculator',
    shortName: 'Flooring',
    category: 'construction',
    description: 'Calculate flooring material needed including waste factor for various floor types.',
    keywords: ['flooring calculator', 'hardwood floor', 'laminate', 'vinyl flooring'],
    mode: 'form',
    icon: 'Layers',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ ENGINEERING (8 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'ohms-law',
    name: "Ohm's Law Calculator",
    shortName: "Ohm's Law",
    category: 'engineering',
    description: 'Calculate voltage, current, resistance, and power using Ohm\'s Law.',
    keywords: ["ohms law calculator", 'voltage current resistance', 'electrical calculator', 'watts'],
    mode: 'form',
    icon: 'Zap',
  },
  {
    slug: 'resistor',
    name: 'Resistor Calculator',
    shortName: 'Resistor',
    category: 'engineering',
    description: 'Calculate resistor values from color bands and vice versa.',
    keywords: ['resistor calculator', 'color code', 'ohm resistor', 'electronic components'],
    mode: 'form',
    icon: 'CircuitBoard',
  },
  {
    slug: 'bandwidth',
    name: 'Bandwidth Calculator',
    shortName: 'Bandwidth',
    category: 'engineering',
    description: 'Calculate download/upload time, data transfer, and internet speed needs.',
    keywords: ['bandwidth calculator', 'download time', 'data transfer', 'internet speed'],
    mode: 'form',
    icon: 'Wifi',
  },
  {
    slug: 'voltage-drop',
    name: 'Voltage Drop Calculator',
    shortName: 'Voltage Drop',
    category: 'engineering',
    description: 'Calculate voltage drop in electrical cables based on length and gauge.',
    keywords: ['voltage drop', 'cable sizing', 'wire gauge', 'electrical voltage'],
    mode: 'form',
    icon: 'Cable',
  },
  {
    slug: 'horsepower',
    name: 'Horsepower Calculator',
    shortName: 'Horsepower',
    category: 'engineering',
    description: 'Convert between mechanical, metric, and electrical horsepower.',
    keywords: ['horsepower calculator', 'hp to kw', 'brake horsepower', 'engine power'],
    mode: 'form',
    icon: 'Gauge',
  },
  {
    slug: 'density',
    name: 'Density Calculator',
    shortName: 'Density',
    category: 'engineering',
    description: 'Calculate density, mass, and volume of materials and substances.',
    keywords: ['density calculator', 'mass volume density', 'material density', 'specific gravity'],
    mode: 'form',
    icon: 'Beaker',
  },
  {
    slug: 'molarity',
    name: 'Molarity Calculator',
    shortName: 'Molarity',
    category: 'engineering',
    description: 'Calculate molarity, molality, and solution concentration for chemistry.',
    keywords: ['molarity calculator', 'concentration', 'moles', 'solution chemistry'],
    mode: 'form',
    icon: 'FlaskConical',
  },
  {
    slug: 'tip-speed',
    name: 'Propeller Tip Speed Calculator',
    shortName: 'Tip Speed',
    category: 'engineering',
    description: 'Calculate propeller or fan tip speed and Mach number.',
    keywords: ['tip speed', 'propeller speed', 'fan tip speed', 'mach number'],
    mode: 'form',
    icon: 'Fan',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ OTHER / MISC (12 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'dice-roller',
    name: 'Dice Roller',
    shortName: 'Dice Roller',
    category: 'misc',
    description: 'Roll virtual dice with various sides and modifiers for games and probability.',
    keywords: ['dice roller', 'roll dice', 'dnd dice', 'random dice', 'rpg dice'],
    mode: 'form',
    icon: 'Dice5',
  },
  {
    slug: 'fuel-cost',
    name: 'Fuel Cost Calculator',
    shortName: 'Fuel Cost',
    category: 'misc',
    description: 'Calculate fuel cost for a trip based on distance, MPG, and gas price.',
    keywords: ['fuel cost calculator', 'gas cost', 'trip fuel', 'driving cost'],
    mode: 'form',
    icon: 'Fuel',
  },
  {
    slug: 'btu',
    name: 'BTU Calculator',
    shortName: 'BTU',
    category: 'misc',
    description: 'Calculate BTU requirements for heating and cooling rooms and buildings.',
    keywords: ['btu calculator', 'heating cooling', 'air conditioner sizing', 'thermal load'],
    mode: 'form',
    icon: 'ThermometerSun',
  },
  {
    slug: 'wind-chill',
    name: 'Wind Chill Calculator',
    shortName: 'Wind Chill',
    category: 'misc',
    description: 'Calculate the feels-like temperature based on wind speed and air temperature.',
    keywords: ['wind chill', 'feels like temperature', 'cold weather', 'wind factor'],
    mode: 'form',
    icon: 'Wind',
  },
  {
    slug: 'dew-point',
    name: 'Dew Point Calculator',
    shortName: 'Dew Point',
    category: 'misc',
    description: 'Calculate dew point and relative humidity from temperature and humidity data.',
    keywords: ['dew point calculator', 'relative humidity', 'weather calculator', 'condensation'],
    mode: 'form',
    icon: 'CloudDrizzle',
  },
  {
    slug: 'heat-index',
    name: 'Heat Index Calculator',
    shortName: 'Heat Index',
    category: 'misc',
    description: 'Calculate the heat index (feels-like temperature) from temperature and humidity.',
    keywords: ['heat index', 'feels like hot', 'humidity heat', 'summer heat'],
    mode: 'form',
    icon: 'Sun',
  },
  {
    slug: 'golf-handicap',
    name: 'Golf Handicap Calculator',
    shortName: 'Golf HCP',
    category: 'misc',
    description: 'Calculate your golf handicap index from recent scores and course ratings.',
    keywords: ['golf handicap', 'handicap index', 'golf score', 'course rating'],
    mode: 'form',
    icon: 'Flag',
  },
  {
    slug: 'tire-size',
    name: 'Tire Size Calculator',
    shortName: 'Tire Size',
    category: 'misc',
    description: 'Compare tire sizes and calculate speedometer error when changing tire size.',
    keywords: ['tire size calculator', 'tire comparison', 'speedometer error', 'wheel size'],
    mode: 'form',
    icon: 'CircleDot',
  },
  {
    slug: 'mileage',
    name: 'Gas Mileage Calculator',
    shortName: 'Mileage',
    category: 'misc',
    description: 'Calculate MPG, fuel efficiency, and cost per mile for your vehicle.',
    keywords: ['gas mileage', 'mpg calculator', 'fuel efficiency', 'miles per gallon'],
    mode: 'form',
    icon: 'Gauge',
  },
  {
    slug: 'tip-splitter',
    name: 'Bill Splitter',
    shortName: 'Bill Split',
    category: 'misc',
    description: 'Split restaurant bills evenly or by item among multiple people.',
    keywords: ['bill splitter', 'split bill', 'restaurant bill', 'share cost'],
    mode: 'form',
    icon: 'Split',
  },
  {
    slug: 'molecular-weight',
    name: 'Molecular Weight Calculator',
    shortName: 'Mol Weight',
    category: 'misc',
    description: 'Calculate molecular weight of chemical compounds from their formulas.',
    keywords: ['molecular weight', 'molar mass', 'chemical formula', 'compound mass'],
    mode: 'form',
    icon: 'Atom',
  },
  {
    slug: 'weather',
    name: 'Weather Calculator',
    shortName: 'Weather',
    category: 'misc',
    description: 'Get current weather and calculate weather-related metrics for any city.',
    keywords: ['weather calculator', 'current weather', 'temperature forecast', 'weather data'],
    mode: 'form',
    icon: 'CloudSun',
    apiPowered: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ GEOMETRY (13 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'polygon-area',
    name: 'Polygon Area Calculator',
    shortName: 'Polygon',
    category: 'geometry',
    description: 'Calculate area of regular polygons: pentagon, hexagon, octagon, and more.',
    keywords: ['polygon area', 'regular polygon', 'hexagon area', 'pentagon area'],
    mode: 'form',
    icon: 'Hexagon',
  },
  {
    slug: 'ellipse',
    name: 'Ellipse Calculator',
    shortName: 'Ellipse',
    category: 'geometry',
    description: 'Calculate area, circumference, and focal points of an ellipse.',
    keywords: ['ellipse calculator', 'ellipse area', 'ellipse circumference', 'foci'],
    mode: 'form',
    icon: 'Circle',
  },
  {
    slug: 'sphere',
    name: 'Sphere Calculator',
    shortName: 'Sphere',
    category: 'geometry',
    description: 'Calculate volume, surface area, and diameter of a sphere.',
    keywords: ['sphere calculator', 'sphere volume', 'sphere surface area', 'ball volume'],
    mode: 'form',
    icon: 'Globe',
  },
  {
    slug: 'cylinder-geo',
    name: 'Cylinder Calculator',
    shortName: 'Cylinder',
    category: 'geometry',
    description: 'Calculate volume, surface area, and lateral area of a cylinder.',
    keywords: ['cylinder calculator', 'cylinder volume', 'pipe volume', 'tube volume'],
    mode: 'form',
    icon: 'Cylinder',
  },
  {
    slug: 'cone',
    name: 'Cone Calculator',
    shortName: 'Cone',
    category: 'geometry',
    description: 'Calculate volume, surface area, and slant height of a cone.',
    keywords: ['cone calculator', 'cone volume', 'cone surface area', 'slant height'],
    mode: 'form',
    icon: 'Cone',
  },
  {
    slug: 'pyramid',
    name: 'Pyramid Calculator',
    shortName: 'Pyramid',
    category: 'geometry',
    description: 'Calculate volume and surface area of square and triangular pyramids.',
    keywords: ['pyramid calculator', 'pyramid volume', 'square pyramid', 'triangular pyramid'],
    mode: 'form',
    icon: 'Triangle',
  },
  {
    slug: 'parallelogram',
    name: 'Parallelogram Calculator',
    shortName: 'Parallelogram',
    category: 'geometry',
    description: 'Calculate area, perimeter, and diagonals of a parallelogram.',
    keywords: ['parallelogram area', 'parallelogram perimeter', 'rhombus area'],
    mode: 'form',
    icon: 'Square',
  },
  {
    slug: 'trapezoid',
    name: 'Trapezoid Calculator',
    shortName: 'Trapezoid',
    category: 'geometry',
    description: 'Calculate area, perimeter, and median of a trapezoid.',
    keywords: ['trapezoid area', 'trapezoid perimeter', 'trapezium area'],
    mode: 'form',
    icon: 'Square',
  },
  {
    slug: 'sector',
    name: 'Circle Sector Calculator',
    shortName: 'Sector',
    category: 'geometry',
    description: 'Calculate area, arc length, and chord length of a circle sector.',
    keywords: ['sector area', 'circle sector', 'arc length', 'chord length'],
    mode: 'form',
    icon: 'PieChart',
  },
  {
    slug: 'segment',
    name: 'Circle Segment Calculator',
    shortName: 'Segment',
    category: 'geometry',
    description: 'Calculate area and arc length of a circle segment.',
    keywords: ['segment area', 'circle segment', 'circular segment'],
    mode: 'form',
    icon: 'PieChart',
  },
  {
    slug: 'distance-2d',
    name: '2D Distance Calculator',
    shortName: '2D Distance',
    category: 'geometry',
    description: 'Calculate distance between two points in a 2D plane.',
    keywords: ['distance calculator', '2d distance', 'point distance', 'euclidean distance'],
    mode: 'form',
    icon: 'Move',
  },
  {
    slug: 'distance-3d',
    name: '3D Distance Calculator',
    shortName: '3D Distance',
    category: 'geometry',
    description: 'Calculate distance between two points in 3D space.',
    keywords: ['3d distance', 'space distance', 'point distance 3d'],
    mode: 'form',
    icon: 'Box',
  },
  {
    slug: 'midpoint',
    name: 'Midpoint Calculator',
    shortName: 'Midpoint',
    category: 'geometry',
    description: 'Find the midpoint between two points in 2D or 3D space.',
    keywords: ['midpoint calculator', 'midpoint formula', 'center point'],
    mode: 'form',
    icon: 'Target',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ STATISTICS (13 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'correlation',
    name: 'Correlation Calculator',
    shortName: 'Correlation',
    category: 'statistics',
    description: 'Calculate Pearson correlation coefficient between two data sets.',
    keywords: ['correlation', 'pearson correlation', 'correlation coefficient', 'r value'],
    mode: 'form',
    icon: 'TrendingUp',
  },
  {
    slug: 'regression',
    name: 'Linear Regression',
    shortName: 'Regression',
    category: 'statistics',
    description: 'Calculate linear regression line, slope, intercept, and R².',
    keywords: ['linear regression', 'regression line', 'least squares', 'best fit line'],
    mode: 'form',
    icon: 'TrendingUp',
  },
  {
    slug: 'binomial',
    name: 'Binomial Distribution',
    shortName: 'Binomial',
    category: 'statistics',
    description: 'Calculate binomial probabilities, mean, variance, and standard deviation.',
    keywords: ['binomial distribution', 'binomial probability', 'bernoulli', 'nCr probability'],
    mode: 'form',
    icon: 'BarChart3',
  },
  {
    slug: 'normal-distribution',
    name: 'Normal Distribution',
    shortName: 'Normal Dist',
    category: 'statistics',
    description: 'Calculate probabilities, z-scores, and percentiles for normal distributions.',
    keywords: ['normal distribution', 'gaussian', 'bell curve', 'probability density'],
    mode: 'form',
    icon: 'Bell',
  },
  {
    slug: 'poisson',
    name: 'Poisson Distribution',
    shortName: 'Poisson',
    category: 'statistics',
    description: 'Calculate Poisson probabilities for rare events.',
    keywords: ['poisson distribution', 'poisson probability', 'rare events', 'lambda'],
    mode: 'form',
    icon: 'BarChart4',
  },
  {
    slug: 'chi-square',
    name: 'Chi-Square Calculator',
    shortName: 'Chi-Square',
    category: 'statistics',
    description: 'Calculate chi-square statistic for contingency tables and goodness of fit.',
    keywords: ['chi square', 'chi-square test', 'goodness of fit', 'contingency table'],
    mode: 'form',
    icon: 'Grid3x3',
  },
  {
    slug: 't-test',
    name: 'T-Test Calculator',
    shortName: 'T-Test',
    category: 'statistics',
    description: 'Perform one-sample and two-sample t-tests.',
    keywords: ['t-test', 'student t test', 'hypothesis testing', 'significance test'],
    mode: 'form',
    icon: 'Activity',
  },
  {
    slug: 'anova',
    name: 'ANOVA Calculator',
    shortName: 'ANOVA',
    category: 'statistics',
    description: 'Calculate one-way ANOVA: F-statistic, sum of squares, and p-value estimate.',
    keywords: ['anova', 'analysis of variance', 'f-test', 'one way anova'],
    mode: 'form',
    icon: 'Layers',
  },
  {
    slug: 'outlier',
    name: 'Outlier Calculator',
    shortName: 'Outlier',
    category: 'statistics',
    description: 'Detect outliers using IQR method and Z-score method.',
    keywords: ['outlier detection', 'outlier calculator', 'iqr method', 'z score outlier'],
    mode: 'form',
    icon: 'AlertTriangle',
  },
  {
    slug: 'percentile',
    name: 'Percentile Calculator',
    shortName: 'Percentile',
    category: 'statistics',
    description: 'Calculate percentiles, quartiles, and deciles for any data set.',
    keywords: ['percentile calculator', 'quartiles', 'deciles', 'percentile rank'],
    mode: 'form',
    icon: 'Percent',
  },
  {
    slug: 'effect-size',
    name: 'Effect Size Calculator',
    shortName: 'Effect Size',
    category: 'statistics',
    description: 'Calculate Cohen\'s d and other effect size measures.',
    keywords: ['effect size', 'cohens d', 'hedges g', 'statistical power'],
    mode: 'form',
    icon: 'Zap',
  },
  {
    slug: 'sampling',
    name: 'Sample Size Calculator',
    shortName: 'Sample Size',
    category: 'statistics',
    description: 'Calculate required sample size for surveys and experiments.',
    keywords: ['sample size', 'survey sample', 'margin of error', 'confidence level'],
    mode: 'form',
    icon: 'Users',
  },
  {
    slug: 'histogram',
    name: 'Histogram Calculator',
    shortName: 'Histogram',
    category: 'statistics',
    description: 'Calculate bin widths, frequencies, and generate histogram data.',
    keywords: ['histogram', 'bin width', 'frequency distribution', 'data bins'],
    mode: 'form',
    icon: 'BarChartHorizontal',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ═══════════════ TRIGONOMETRY (13 calculators) ═══════════════
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    slug: 'sin-cos-tan',
    name: 'Sin Cos Tan Calculator',
    shortName: 'Sin/Cos/Tan',
    category: 'trigonometry',
    description: 'Calculate sine, cosine, and tangent for any angle in degrees or radians.',
    keywords: ['sin cos tan', 'sine calculator', 'cosine calculator', 'tangent calculator'],
    mode: 'form',
    icon: 'Waves',
  },
  {
    slug: 'inverse-trig',
    name: 'Inverse Trig Calculator',
    shortName: 'Arcsin/etc',
    category: 'trigonometry',
    description: 'Calculate arcsin, arccos, arctan, and other inverse trig functions.',
    keywords: ['arcsin', 'arccos', 'arctan', 'inverse sine', 'inverse trig'],
    mode: 'form',
    icon: 'Waves',
  },
  {
    slug: 'unit-circle',
    name: 'Unit Circle Calculator',
    shortName: 'Unit Circle',
    category: 'trigonometry',
    description: 'Find coordinates and trig values for any angle on the unit circle.',
    keywords: ['unit circle', 'unit circle coordinates', 'trig values', 'sine cosine unit circle'],
    mode: 'form',
    icon: 'Circle',
  },
  {
    slug: 'law-of-sines',
    name: 'Law of Sines Calculator',
    shortName: 'Law of Sines',
    category: 'trigonometry',
    description: 'Solve triangles using the Law of Sines: a/sin(A) = b/sin(B) = c/sin(C).',
    keywords: ['law of sines', 'sine rule', 'solve triangle', 'triangle angles'],
    mode: 'form',
    icon: 'Triangle',
  },
  {
    slug: 'law-of-cosines',
    name: 'Law of Cosines Calculator',
    shortName: 'Law of Cosines',
    category: 'trigonometry',
    description: 'Solve triangles using the Law of Cosines: c² = a² + b² - 2ab cos(C).',
    keywords: ['law of cosines', 'cosine rule', 'solve triangle sides', 'triangle calculator'],
    mode: 'form',
    icon: 'Triangle',
  },
  {
    slug: 'trig-identities',
    name: 'Trig Identity Verifier',
    shortName: 'Trig Identities',
    category: 'trigonometry',
    description: 'Verify and simplify common trigonometric identities.',
    keywords: ['trig identities', 'trigonometric identities', 'sin squared', 'cos squared'],
    mode: 'form',
    icon: 'CheckCircle',
  },
  {
    slug: 'polar-rectangular',
    name: 'Polar ↔ Rectangular',
    shortName: 'Polar/Rect',
    category: 'trigonometry',
    description: 'Convert between polar coordinates (r,θ) and rectangular coordinates (x,y).',
    keywords: ['polar coordinates', 'rectangular coordinates', 'polar to rectangular', 'cartesian'],
    mode: 'form',
    icon: 'ArrowLeftRight',
  },
  {
    slug: 'deg-rad',
    name: 'Degrees ↔ Radians',
    shortName: 'Deg/Rad',
    category: 'trigonometry',
    description: 'Convert angles between degrees, radians, and gradians.',
    keywords: ['degrees to radians', 'radians to degrees', 'angle conversion', 'gradians'],
    mode: 'form',
    icon: 'RotateCcw',
  },
  {
    slug: 'trig-graph',
    name: 'Trig Function Evaluator',
    shortName: 'Trig Eval',
    category: 'trigonometry',
    description: 'Evaluate sin, cos, tan, sec, csc, cot for any angle with full working.',
    keywords: ['trig functions', 'secant cosecant cotangent', 'evaluate trig', 'all trig functions'],
    mode: 'form',
    icon: 'LineChart',
  },
  {
    slug: 'reference-angle',
    name: 'Reference Angle Calculator',
    shortName: 'Reference',
    category: 'trigonometry',
    description: 'Find the reference angle for any angle in standard position.',
    keywords: ['reference angle', 'acute angle', 'standard position', 'coterminal angle'],
    mode: 'form',
    icon: 'Compass',
  },
  {
    slug: 'coterminal',
    name: 'Coterminal Angle Calculator',
    shortName: 'Coterminal',
    category: 'trigonometry',
    description: 'Find positive and negative coterminal angles for any given angle.',
    keywords: ['coterminal angles', 'coterminal', 'angles with same terminal side'],
    mode: 'form',
    icon: 'RefreshCw',
  },
  {
    slug: 'trig-equation',
    name: 'Trig Equation Solver',
    shortName: 'Trig Equation',
    category: 'trigonometry',
    description: 'Solve basic trigonometric equations like sin(x) = a, cos(x) = b.',
    keywords: ['trig equation', 'solve sin x', 'solve cos x', 'trigonometric equation'],
    mode: 'form',
    icon: 'FunctionSquare',
  },
  {
    slug: 'hyperbolic',
    name: 'Hyperbolic Functions',
    shortName: 'Hyperbolic',
    category: 'trigonometry',
    description: 'Calculate sinh, cosh, tanh, and their inverses.',
    keywords: ['hyperbolic sine', 'sinh cosh tanh', 'hyperbolic functions', 'hyperbolic trig'],
    mode: 'form',
    icon: 'Activity',
  },
]

export function getCalculatorBySlug(slug: string): CalculatorEntry | undefined {
  return calculators.find((c) => c.slug === slug)
}

export function getCalculatorsByCategory(category: CalculatorCategory): CalculatorEntry[] {
  return calculators.filter((c) => c.category === category)
}

export function getAllSlugs(): string[] {
  return calculators.map((c) => c.slug)
}

export function getApiPoweredCalculators(): CalculatorEntry[] {
  return calculators.filter((c) => c.apiPowered)
}
